.gitignore
This PR simplifies excluding `.idea` directory.
=> Simplify IDEA settings exclusion

.idea/inspectionProfiles/Project_Default.xml, gradle/dependencies.gradle
This PR adds Google Truth dependencies.
=> Adopt Truth

.idea/inspectionProfiles/Project_Default.xml
This small PR enables the support of `TSLint` inspection.
=> Enable TS-Lint inspection.

gradle/model-compiler.gradle
This PR changes the names of method factories defines in `base`.
=> Rename method factories

README.md
Minor config README.md text fixes: language-, style-, formatting-related fixes.
=> config README.md revised and edited

gradle/dependencies.gradle, gradle/generate-pom.gradle
This PR exposes the `generatePom` task (see https://github.com/SpineEventEngine/config/pull/66).
=> Expose `generatePom` task in the `deps` Gradle script

gradle/dependencies.gradle
This PR bumps Protobuf to the latest version.
=> Bump Protobuf

gradle/update-gh-pages.gradle
In this PR we fix the git repository reference in the `update-gh-pages.gradle`, as well as adding more output if the build fails.
=> Fix git reference

gradle/buildSrc/build.gradle.kts
Here we document the `buildSrc/build.gradle.kts` file specifics.
=> Document build script

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt, gradle/dependencies.gradle, quality/pmd.xml
In this PR we update the PMD version to `6.24.0`.
=> Update PMD version

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt, gradle/dependencies.gradle, gradle/javac-args.gradle
This PR forces the build to fail on compiler warnings. This includes Error Prone warnings.
Before, warnings were logged, but the build kept running.
=> Fail build on compiler warnings

CONTRIBUTING.md, pull
This PR adds updated text of Contributor's Guide to shared configuration and makes  the `config` update this text when `pull`ed.
=> Update `CONTRIBUTING.md` on `pull`

scripts/trigger-librarian.sh, scripts/trigger-publishing.sh
This PR adds the script that launches the build of the [publishing application](https://github.com/SpineEventEngine/publishing) and some instructions on when to execute the script.
=> Add the script that invokes the publishing application

CODE_OF_CONDUCT.md, pull
This PR brings a `CODE_OF_CONDUCT.md` file from the [Contributor Covenant](https://www.contributor-covenant.org/).
=> Add `CODE_OF_CONDUCT.md`

CODE_OF_CONDUCT.md, gradle/dart/pub-publish-tasks.gradle, pull
This PR brings the latest changes from the `master` branch of this repository to the `2.x-jdk8-master` branch.
=> Back-merge from `master`

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
This PR resolves the latest transitive dependency conflicts.
=> Force transitive dependencies

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/IncrementGuard.kt, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
This changeset updates the `2.x-jdk8-master` branch with the latest changes performed in `master` recently.
=> [2.x-jdk8] Back-merge from `master`

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
This PR:
* Encapsulates dependencies so that versions are in the same object with artifact IDs that use them.
* Forces Kotlin dependencies.
* Bumps some dependency versions.
=> Consolidate dependency declarations

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt, gradle/publish.gradle
In this PR we fix a compilation error in a Kotlin script and a couple of errors in the build scripts.
=> Fix Kotlin compilation

scripts/decrypt.sh
This PR adds the `decrypt.sh` script for decrypting files on GitHub Actions CI.
=> `decrypt.sh` script

gradle/update-gh-pages.gradle
This PR fixes reference to a utility class made in a `.gradle` script.
=> Fix utility class reference

buildSrc/src/main/kotlin/io/spine/internal/gradle/Scripts.kt
This PR fixes the path reference to moved Groovy scripts.
=> Fix new common path

buildSrc/src/main/groovy/dependencies.gradle
This PR fixes reference to javac plugin of ErrorProne.
=> Fix ErrorProne plugin ref.

buildSrc/src/main/groovy/publish-proto.gradle, buildSrc/src/main/kotlin/io/spine/internal/gradle/DependencyResolution.kt, gradle/wrapper/gradle-wrapper.properties
This PR adds more changes for Gradle scripts compatibility with v7 API.
=> More Gradle 7 compatibility changes

buildSrc/src/main/kotlin/io/spine/internal/gradle/RunBuild.kt
This PR improves diagnostics of a build process started by the `RunBuild` task.
=> Improve child build process diags

buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
The new Cloud Artifact Registry repos need credentials for publishing.
Previously, we fetched them eagerly and expected them to always be available. However, this is not the case in a dev environment. Thus, we allow Google credentials to be absent, just like with all the other credentials.
=> Laid-back Google credentials

.github-workflows/publish.yml
This PR:
* Fixes the paths to the keys in the `publish.yml`.
* Uses repository name variable for publishing, instead of a hard-coded value.
=> Fix key paths

.codecov.yml, .github-workflows/build-on-ubuntu.yml, pull
This PR improves Codecov settings, fixing ignored paths, and allowing threshold. 
These settings are now always applied, when new `config` is applied to a repository.
Also, the name of Ubunity OS was fixed in corresponding workflow file.
=> Codecov settings

buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
This PR fixes the issue with hard-coded repository name (`"base-types"`), which was used inside the calls to `doApplyGitHubPackages()` and `RepositoryHandler.applyGitHubPackages()`. Now these methods accept additional parameter `shortRepositoryName`, which should have the name of the repository build script of which makes these calls.
This is a breaking change. The build scripts must be adjusted when new `config` containing this change is applied.
=> Fix hard-coded short repository name

buildSrc/src/main/kotlin/io/spine/internal/gradle/report/coverage/JacocoConfig.kt
This PR adds missing space character in the diagnostics message of `JacocoConfig`.
=> Add missing space char

buildSrc/src/main/kotlin/io/spine/internal/dependency/AutoCommon.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/AutoService.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/AutoValue.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/CheckStyle.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/CheckerFramework.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/CommonsCli.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ErrorProne.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/GoogleApis.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/GoogleCloud.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Gson.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/HttpClient.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/J2ObjC.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Netty.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Pmd.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Roaster.kt
This PR advances dependencies Protobuf, gRPC, and some other dependencies.
=> Bump Protobuf, gRPC, and other dependencies

buildSrc/src/main/kotlin/io/spine/internal/dependency/CheckerFramework.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Flogger.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Jackson.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/JavaJwt.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Klaxon.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Plexus.kt, gradle/wrapper/gradle-wrapper.properties
This PR advances Gradle to 7.3.3 and some other dependencies. Please see commit messages for details.
=> Bump Gradle and other dependencies

.idea/misc.xml, buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ErrorProne.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
This PR bumps versions of several selected dependencies. Please see commit messages for the version numbers.
These versions were tested against the `tool-base` project.
=> Bump dependencies

.github-workflows/build-on-ubuntu.yml, .github-workflows/build-on-windows.yml, .github-workflows/ensure-reports.updated.yml, .github-workflows/increment-guard.yml, .github-workflows/publish.yml, .github/workflows/gradle-wrapper-validation.yml, .idea/misc.xml, README.md
This PR updates GitHub workflows with action versions already used by some of the subprojects.
=> Use action versions already used by subprojects

buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
This PR addresses a recently discovered vulnerability in Protobuf libraries.
=> Update Protobuf version

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR extends the `Spine` dependency object to serve McJava dependencies.
=> Add `Spine` properties for McJava

buildSrc/src/main/kotlin/BuildExtensions.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/JUnit.kt
This PR:
1. Updates JUnit dependencies.
2. Extract task name variables.
=> Bump JUnit, extract task name vars

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/CheckerFramework.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ErrorProne.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Gson.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Guava.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kover.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Netty.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Roaster.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR updates external and internal dependencies.
=> Bump versions

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/KotlinX.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR brings changes to the build configuration recently introduced in ProtoData and McJava.
=> Improve and update dependencies

buildSrc/src/main/kotlin/io/spine/internal/dependency/Clikt.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/IncrementGuard.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/PublishingRepos.kt
This PR propagates version increment fix recently [introduced in `tool-base`.](https://github.com/SpineEventEngine/tool-base/pull/91).
`Clikt` dependency object was also added.
=> Fix version increment check

buildSrc/src/main/kotlin/DependencyResolution.kt, buildSrc/src/main/kotlin/io/spine/dependency/build/ErrorProne.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Asm.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Grpc.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/JavaPoet.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/JavaX.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Roaster.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ArtifactVersion.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/BaseTypes.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Change.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/CoreJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Logging.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/McJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ModelCompiler.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Reflect.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Spine.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/TestLib.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Text.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Time.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ToolBase.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt, buildSrc/src/main/kotlin/jvm-module.gradle.kts
This PR brings updates to local dependency objects recently adopted in Validation.
=> Bring updates from Validation

buildSrc/src/main/kotlin/io/spine/dependency/lib/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/KotlinPoet.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/KotlinX.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/test/KotlinCompileTesting.kt
This PR brings more changes to dependency objects recently adopted in McJava.
=> Add latest dependency changes from McJava

buildSrc/src/main/kotlin/io/spine/dependency/local/McJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt
This PR applies the latest versions of ProtoData and McJava.
=> Bump ProtoData and McJava

.github/workflows/gradle-wrapper-validation.yml, buildSrc/src/main/kotlin/BuildExtensions.kt, buildSrc/src/main/kotlin/compile-protobuf.gradle.kts, buildSrc/src/main/kotlin/io/spine/gradle/protobuf/ProtoTaskExtensions.kt, buildSrc/src/main/kotlin/jvm-module.gradle.kts
This PR adds updates recently [made in Base](https://github.com/SpineEventEngine/base/pull/864).
=> Bring updates from Base

buildSrc/src/main/kotlin/io/spine/dependency/Dependency.kt, buildSrc/src/main/kotlin/io/spine/dependency/boms/Boms.kt, buildSrc/src/main/kotlin/io/spine/dependency/boms/BomsPlugin.kt, buildSrc/src/main/kotlin/io/spine/dependency/kotlinx/Coroutines.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Coroutines.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Grpc.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Jackson.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/KotlinX.kt, buildSrc/src/main/kotlin/io/spine/dependency/test/JUnit.kt, buildSrc/src/main/kotlin/io/spine/gradle/protobuf/ProtoTaskExtensions.kt
This PR brings updates recently adopted in Validation subproject.
=> Add changes from Validation

buildSrc/src/main/kotlin/io/spine/dependency/local/BaseTypes.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/CoreJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/McJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ToolBase.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt, buildSrc/src/main/kotlin/io/spine/dependency/test/KotlinCompileTesting.kt
This PR brings dependency updates from latest McJava.
=> Updates from McJava
