SpineEventEngine/config

scripts/util/remove_finals.py
This PR introduces a script which allows to remove `final` modifier from all local variables in the Java code.
The script takes the directory with Java files as an input and performs refactoring in-place.
The only prerequisite for running the script is having `Python 2.7` installed in the system.
The script is proposed to be located in the new directory `scripts/util`.
=> Add script removing `final` modifier from local variables

gradle/dependencies.gradle
In this PR we add the Grpc dependencies required for `core-java`.
Also, in this PR we fix a typo in the dependency strings. One string was used 3 times. Now, one of the usages is deleted and one is changed to another value.
=> gRPC Dependencies

ext.gradle, gradle/dependencies.gradle, gradle/publish-proto.gradle
This PR adds a publish-proto.gradle under config. 
This script allows generating a JAR from all proto definitions available at a classpath (the definitions from `sourceSets.main.proto` and the proto files extracted from the JAR dependencies of the project.)
The script is used by simply applying it in the Gradle project.
=> Add publish-proto Gradle script

gradle/publish-proto.gradle
This PR stops `mavenProto` publication from generating the default JAR artifact.
Previously it produced two artifacts: `jar` and `assembleProto`. Now it’s just single `assembleProto` artifact.
=> Make publish-proto script generate single JAR

.idea/inspectionProfiles/Project_Default.xml
In this PR we configure the `UnstableApiUsage` IDEA inspection. The severity is `WEAK WARNING`. 
An example of such API is `com.google.common.collect.Streams` class.
=> Add `UnstableApiUsage` Inspection Config

gradle/add-javadoc-tags.gradle, gradle/dependencies.gradle
This PR resolves issue https://github.com/SpineEventEngine/config/issues/14.
Now the new Javadoc tags - `@apiNote`, `@implSpec` and `@implNote` - can be enabled in the build using:
```
apply from: deps.scripts.addJavadocTags
```
=> Add Gradle script enabling new Javadoc tags

.idea/inspectionProfiles/Project_Default.xml
This PR enables the `AssignmentToCollectionFieldFromParameter` warning in the common IntelliJ IDEA configuration.
Previously, the check was disabled by default, and the compiler said nothing when the `Collection` was copied by reference from the method parameter. 
Now, it emits a warning and suggests doing deep copy instead.
The private methods are ignored by this check.
=> Enable `AssignmentToCollectionFieldFromParameter` inspection in Idea

.idea/inspectionProfiles/Project_Default.xml
In order to avoid warnings on `@Nested` test suites, we allow inner test classes to be non-static even if they could be static.
=> Allow non-static inner classes in tests

.idea/inspectionProfiles/Project_Default.xml, gradle/dependencies.gradle
This PR removes JUnit 4 and JUnit vintage runner dependencies.
Also, the convention for test methods naming was changed. Now, the names should be in `camelCase` instead of `snake_case`. So, the related inspection profile was enabled.
=> Remove JUnit 4 dependencies

gradle/dependencies.gradle
This PR is a part of https://github.com/SpineEventEngine/web/pull/36.
It adds the new `web` dependencies to the Spine common dependencies so they can be easier re-used by the other projects.
Added dependencies:
1) Google HTTP Client, version `1.26.0`
2) Apache Commons Validator, version `1.4.0`
3) AppEngine API SDK, version `1.9.67`
=> Add new dependencies from `web`

gradle/jacoco.gradle
This PR improves `jacoco.gradle` script.
Now the script will work if the root project or its subprojects aren't Java projects. Previously, it tried to aggregate coverage reports from all subprojects and some of them might be non-Java projects.
Also, if subprojects are configured separately, the script should wait until the evaluation of these subprojects. It is needed to say which of the subprojects are Java projects and it is done using `evaluationDependsOnChildren()`.
=> Support non-Java subprojects by `jacoco.gradle` script

gradle/javadoc-options.gradle
This PR adds an option to the `javadoc` gradle task that explicitly states UTF-8 encoding of source files.
This broadens the range of supported environments, since during the execution of the `javadoc` task under some Windows-based environments, encoding different from UTF-8 is assumed, resulting in unrecognized symbols.
=> Explicit UTF-8 encoding of source files during generation of javadoc

gradle/javac-args.gradle
This PR fixes #38 issue.
Now Gradle Java compile tasks are set to use `UTF-8` as the default encoding,
=> Force UTF-8 encoding for Java compile tasks

gradle/dependencies.gradle, gradle/js/build-tasks.gradle, gradle/js/js.gradle, gradle/js/npm-cli.gradle, gradle/js/npm-publish-tasks.gradle, gradle/js/update-package-version.gradle
This PR brings common Gradle tasks for JavaScript modules.
In particular:
- Tasks to run NPM commands from Gradle scripts.
- Tasks to install NPM dependencies and clean them up.
- A task to update a version of a `package.json`.
- A bunch of tasks for publishing to NPM.
=> Introduce common scripts for JavaScript modules

gradle/js/npm-publish-tasks.gradle
This PR fixes `prepareJsPulication`. Previously, this task cleaned up the publication directory, so it was not possible to make `prepareJsPublication` depend on other tasks.
The similar problem is described in this [issue](https://github.com/gradle/gradle/issues/1012).
=> Prevent side effects of `prepareJsPublication` task

gradle/dependencies.gradle, gradle/pmd.gradle, quality/pmd.xml
This PR intents to configure a PMD static code analysis during the Gradle build.
In scope of this request a set of PMD rules that are currently being used at Codacy is composed as XML. If any of the rules is violated, the build fails.
The generated codebase and the test sources are currently excluded from the analysis.
There is a `deps.scripts.pmd` script exported for a convenience.
=> Add PMD rules and the Gradle configuration script

gradle/checkstyle.gradle, gradle/dependencies.gradle, quality/checkstyle-suppressions.xml, quality/checkstyle.xml
This PR intents to configure a Checkstyle static code analysis during the Gradle build.
In scope of this request a set of Checkstyle modules that are currently being used at Codacy is composed as XML. If any of the modules emits a violation, the build fails.
A presense of `TODO` comments is covered with a Checkstyle module, but it is configured to emit warnings, not errors.
The generated codebase and the test sources are currently excluded from the analysis.
There is a `deps.scripts.checkstyle` script exported for a convenience.
=> Add Checkstyle rules and the Gradle configuration script

.gitattributes
The aim of the PR is to refine current Git `autocrlf` configuration in order to allow Windows users to use available `.sh` scripts with [WSL](https://docs.microsoft.com/en-us/windows/wsl/faq).
Always use `CRLF` for `*.bat` files and `LF` for `*.sh` files. Use `LF` for `gradlew` and `pull` scripts.
=> Refine default Git autocrlf configuration

gradle/js/build-tasks.gradle
In this PR the "testJs" task was added to the set of JS-build tasks defined in the `/gradle/js/build-tasks.gradle`.
The `check` task is made dependent on `testJs` execution. Note, if the Gradle task graph contains `test` task, the `testJs` task will run __after__ it.
=> Add "testJs" Gradle task.

gradle/dependencies.gradle
To avoid the version clashes during the build, this PR enables a forced version of Gradle Protobuf plugin.
=> Force Gradle Protobuf plugin version

gradle/js/build-tasks.gradle
The goal of this PR is to make JS builds to fail if installed dependencies contain vulnerabilities.
The JS-build tasks for installation of module dependencies: 
- `installNodePackages` - Installs the module dependencies using the `npm install` command. The `npm install` command is executed with the vulnerability check disabled since it cannot fail the task execution despite on vulnerabilities found;
- `auditNodePackages` - Audits the module dependencies using the `npm audit` command. Sets the minimum level of vulnerability for `npm audit` to exit with a non-zero exit code to "high".
- `installDependencies` - Installs the module dependencies and checks them for vulnerabilities. Depends on `installNodePackages` and `auditNodePackages` execution; 
This PR addresses …
=> Fail JS builds if NPM dependencies contain vulnerabilities.

gradle/model-compiler.gradle
The default Model Compiler configuration is now published as a `model-compiler` gradle script.
The script should be applied to every project that tends to have Spine code generation defaults.
Applying such configuration is mandatory for projects that use the version of the `base` module where the defaults are already not configured in Java (see [base#369](https://github.com/SpineEventEngine/base/issues/369) for details).
=> Add default Model Compiler configuration

gradle/dependencies.gradle
I've added `modelCompiler` shortcut to `deps.scripts`.
=> Add model-compiler configuration to scripts

gradle/license-report-project.gradle
This PR adjusts the license report scripts to avoid including the dependencies onto Spine artifacts into the report.
=> Ignore `io.spine.tools` group to report licenses only for 3rd-party

gradle/license-report-project.gradle
This PR adds `io.spine.gcloud` group to the list of ignored groups during the composition of license report.
=> Ignore `io.spine.gcloud` group from license report

gradle/test-output.gradle
The new logging configuration prints all necessary exception information directly to the console and thus we do not really need to check the test suite report to find out what happened in the test.
=> Show full stacktraces in case of an exception during tests

gradle/js/build-tasks.gradle
See https://github.com/SpineEventEngine/config/issues/64
=> Disable audit of NPM packages for JS build pipeline.

gradle/generate-pom.gradle
This PR fixes https://github.com/SpineEventEngine/config/issues/37.
A script is added that can be applied to a project to generate a `pom.xml` file that contains first-level dependencies of the project as well as its subprojects.
The generated `pom.xml` file is not usable for `maven` build tasks, it is only usable for dependency lookup.
Additionally, the `clean` task of the project that applies the script deletes the generated `pom.xml` file.
=> Generate pom.xml with dependencies

gradle/generate-pom.gradle
This PR fixes the layout of the `pom.xml` file that contains all first-level dependencies.
Example of the `pom.xml` with fixed layout can be found [here](https://gist.github.com/serhii-lekariev/37c1c23b9569c2c3f5147ba429c23f43).
=> Fix generated POM layout.

gradle/dependencies.gradle
This PR adds `Roaster` library dependencies for the convenient reusage in Spine modules. 
Previously we had a library version, but not the dependencies themselves.
Is a part of https://github.com/SpineEventEngine/base/pull/430.
=> Add `Roaster` dependencies

gradle/slowTests.gradle
This PR adds the `slowTests.gradle` plugin script which configures JUnit tests to skip the `"slow"` tests by default and execute them when required.
=> Slow tests script

gradle/generate-pom.gradle
This PR makes it so the `clean` task of any project that `applies` from the `generatePom` script does not delete the `pom.xml`.
The change is made to match the behavior of the `generateLicenseReport`.
=> Omit `pom.xml` deletion.

gradle/javac-args.gradle
Before this PR the Spine build failed with some weird errors (ErrorProne failures, `NoClassDefFound`s etc) if built with non-Java 8 JDK. For a newcomer, it looked like she did something wrong, and it should have worked.
As long as we only support JDK 8 as a build runtime, we should say so directly.
=> Fail the build if JDK is not JDK 8. 

gradle/dependencies.gradle, gradle/jacoco.gradle, gradle/publish.gradle
This PR updates the usage of JaCoCo plugin by migrating to new JaCoCo API instead of a deprecated one.
Also, the `GroovyAssignabilityCheck` warning suppressions were removed, as the corresponding [IDEA issue](https://youtrack.jetbrains.com/issue/IDEA-141744) (and related to it) has been resolved effectively starting IDEA 2019.2.
=> Migrate to new JaCoCo API and remove Groovy warning suppressions

gradle/publish-proto.gradle, gradle/publish.gradle
In Gradle v5.6 the behaviour of publication config has been changed. Now it is impossible to have more than one publication with the same group ID, artifact name, and version. This breaks the mechanism of publishing `-proto` artifacts in `core-java`.
In order to work this around, we now publish all the artifacts in a single publication. The artifacts are collected through the `archives` configuration.
This is also more pluggable and helps configure to publish more artifacts in separate projects without changing the `config`.
=> Fix `-proto` artifact publishing

gradle/dependencies.gradle, gradle/js/configure-proto.gradle
This PR extracts a common configuration of the JS-based Spine projects to a separate script.
Currently, the Protobuf configuration across `users`, `web` and [`money`](https://github.com/SpineEventEngine/money/pull/14) is almost the same.
This PR extracts the common traits to a new script `configure-proto.gradle`.
=> Extract common Proto JS configuration

gradle/dependencies.gradle
This PR updates the Guava version.
Also, it forces the version of `org.codehaus.mojo:animal-sniffer-annotations` to `1.18` — to resolve the conflict with `1.17` version of the same library.
=> Update Guava to `28-1-jre`

gradle/dependencies.gradle
The [vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2019-16335) was discovered in the Jackson Databind library pre-`2.9.10`.
This PR updates the version to fix the vulnerability in dependent repositories.
=> Update the Jackson Databind version to `2.9.10`

gradle/dart/build-tasks.gradle, gradle/dart/pub-cli.gradle
This PR introduces the basic Gradle scripts which manage a Dart module.
Only the most common configuration is extracted into `config`. Some minor additional config may still be required on a case-to-case basis.
=> Dart Gradle scripts

gradle/dependencies.gradle, gradle/publish.gradle
Since the recent change of versioning conventions, all of our artifacts were published into the "releases" repository due to the check which determined the target repository from the version.
Previously, the requirement was that `SNAPSHOT` versions had `-SNAPSHOT` at the end. This is no longer the case as `SNAPSHOT` versions now may end with a build number (e.g. `1.1.3-SNAPSHOT+1`).
This PR makes the publishing script account for the possibility of build numbers.
=> Fix `SNAPSHOT` pattern

gradle/model-compiler.gradle
This PR extends the default configuration of Spine Model Compiler to apply the `io.spine.base.EntityState` interface to all entity state messages.
See https://github.com/SpineEventEngine/base/pull/494.
Note: `config` with these changes is usable starting from Spine version `1.2.0`.
=> `EntityState` marker interface

gradle/dependencies.gradle
This PR is a part of https://github.com/SpineEventEngine/web/pull/125.
It adds `commons-cli:commons-cli` to the forced dependencies. 
This became necessary after updating to a new Gretty version in `spine-web`.
=> Force `commons-cli` lib version

gradle/model-compiler.gradle
This PR is a part of [base#508](https://github.com/SpineEventEngine/base/pull/508).
It enables the generation of strongly-typed columns and messages for all Model Compiler users by default.
=> Nested classes generation configuration

gradle/dependencies.gradle
Recently, GitHub has detected a vulnerability [reported in Checkstyle 8.28](https://github.com/SpineEventEngine/time/network/alert/pom.xml/com.puppycrawl.tools:checkstyle/open).
This changeset updates the Checkstyle version to 8.29 in which it was fixed.
=> Update Checkstyle plugin version to 8.29

gradle/js/build-tasks.gradle
This PR enables the NPM audit for the JS packages.
The audit level is set to `critical` so the build fails only if critical vulnerabilities are discovered. For all other cases, the audit log is just printed to the console.
=> Enable NPM audit

gradle/dependencies.gradle, scripts/update-gh-pages.gradle
This PR adds the Gradle script for publishing generated docs and GitHub Pages. The script is moved from `core-java` with a couple of significant changes:
1. The links will now look like `<repo name>/reference/<project name>` instead of `<repo name>/javadoc/<project name>`.
2. The docs for previous versions will be stored under `<repo name>/reference/<project name>/v/<version number>`. The docs for the current version will be both stored under the non-versioned path (as by point 1) and under the versioned path.
3. To add extra docs to publish, the user should append the `ext.generatedDocs` file collection.
4. Extra files are not required anymore, except for the credential file. See the script header for the full preconditions.
=> Pages publishing script

gradle/update-gh-pages.gradle, scripts/register-ssh-key.sh
This PR extracts a bash script into a separate file.
By default, `eval` function is not supported by the Java process execution mechanism. Thus, we extract it into a separate file and run It with Bash.
=> Extract script

.idea/inspectionProfiles/Project_Default.xml
Since recently, the IDEA started reporting an `UnnecessaryLocalVariable` warning on constructs such as:
```java
boolean result = repositories.contains(repository);
return result;
```
Such variables have a great value for debugging as well as for readability.
The change in the IDE behaviour is probably related to the new version.
In this PR we disable the check.
=> Turn `UnnecessaryLocalVariable` inspection off

gradle/filter-internal-javadoc.gradle, gradle/javadoc-options.gradle, gradle/update-gh-pages.gradle
This PR extracts Javadoc options and uses them for the task of removing `@Internal` elements of API from generated Javadocs.
Also the error message for publishing Javadocs from non-CI environment is improved.
=> Constants for javadoc options

pull, pull.bat
Backticks in `echo` caused the `pull` script to fail. Now we remove them.
=> Remove backticks from `pull`

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
In this PR we add comments on why we suppress some warnings in `deps.kt`.
=> Comment suppressions

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
It's a commodity in our projects to exclude `protobuf-lite` artifacts from runtime. In this PR we add a method to do just that.
=> Exclude `protobuf-lite`

gradle/buildSrc/build.gradle.kts, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/CheckVersionIncrement.kt, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/IncrementGuard.kt
In this PR we implement the `IncrementGuard` plugin.
Before, PRs could override existing versions of Spine libraries intentionally or otherwise. This is a bad practice in general. It also may result in an incompatible change within a single version of the library. This kills any build which depends on that library.
In this PR we introduce the `IncrementGuard` Gradle plugin. The plugin creates the `checkVersionIncrement`  task which fails of the current version of the library has already been published to the Maven repository.
Note that the task checks the version upon all the matching artifacts present in the Maven repository, not only upon the latest one.
The `checkVersionIncrement`  task runs upon `check`.
Fixes [this issue](https://github.com/SpineEventEngine/base/issues/537) in …
=> Increment guard

gradle/buildSrc/build.gradle.kts, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/CheckVersionIncrement.kt, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/IncrementGuard.kt, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/RunBuild.kt, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
With Kotlin we are able to place script plugins into the `buildSrc` dir. Those plugins become [precompiled](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins).
At this point, this is the only usable way in which we can develop custom script plugins which use other Gradle plugins. Just placing a `.gradle.kts` file and applying it via `apply(from = "...")` is flawed, as the file cannot use any type-safe accessors for the Gradle model.
In this repository, we prepare the `buildSrc` project for those plugins.
In library repositories, we may define custom script plugins and place them under `buildSrc/src/main/kotlin`. For example, `custom-jar-magic.gradle.kts`:
```kotlin
plugins {
java
}
tasks.jar {
exclude("**/*.properties")
}
```
Then, such plugins become …
=> Allow custom compiled scripts

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
In this PR I have added the `annotation-api` dependency that is required for the Spine `protoc` plugin in order to be run safely with Java11.
=> Add `javax.annotation-api` dependency

scripts/publish-artifacts.sh
In this PR I modified the publishing script to fail the build if the publishing was not successful.
=> Fail build during publishing and print stacktrace if any

scripts/publish-artifacts.sh
This change is an attempt to make sure the publishing process itself could use more memory.
=> Specify the -Xmx for the publishing process itself.

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/CheckVersionIncrement.kt
Allow repositories that were never published before (and thus have no metadata) to pass the check.
An example here the `pubsub` module I'm currently adding to `gcloud` repository. It was never published before and it's not possible to pass the check now.
=> Loose increment version check.

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
This PR updates the version of `jackson-databind`.
See dependabot: https://github.com/SpineEventEngine/web/pull/147.
=> Update jackson-databind version

gradle/update-gh-pages.gradle
The Gradle script which publishes Javadoc to spine.io excludes the doc for components marked as `@Internal`. This is handy for external users, who might try to navigate the framework API via Javadoc. However, the module which configures the Javadoc filtering is a part of `base`, which makes it impossible to publish `base` (due to the bootstrapping problem).
In this PR we make the dependency between the Gradle script and the Javadoc filter agile. By default, `@Internal` doc won't be published. With a single line of Gradle config, the dependency may be removed, allowing for the Gradle script to be used in `base` but making it publish all the doc without filtering it.
To allow publishing all the Javadoc, set the value of `ext.allowInternalJavadoc` to `true`:
```gradle
ext { …
```
=> Add a setting to allow `@Internal` Javadoc

gradle/update-gh-pages.gradle
In this PR we address an error introduced in #134. The internal Javadoc exclusion condition is inverted to fit the purpose of the condition check.
=> Fix Javadoc exclusion logic

gradle/model-compiler.gradle
Previously, the default `modelCompiler` configuration referenced the `columns` configuration flag.
In this changeset, it is renamed to `entityQueries` to reflect the incoming changes to the `base` repository.
Other changes include the update to the documentation of the `modelCompiler` configuration and a new package name for one of the classes referenced by the configuration.
=> Rename the property of the model compiler

gradle/buildSrc/build.gradle.kts, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/IncrementGuard.kt
This PR modifies the `IncrementGuard` to run version increment check only during Travis Pull Request jobs.
The `checkVersionIncrement` task will no longer be executed:
1. during local builds;
2. for `merge` commits;
3. when building individual branches;
4. during any other CI checks rather than Travis build.
This change will allow CI checks to pass in situations outside of the "normal" build cycle, for example, when `master` should be re-built after artifacts are already published, or when a git tag is created.
Fixes #139.
=> Run the `CheckVersionIncrement` only during Pull Request builds

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/IncrementGuard.kt, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt, gradle/checkstyle.gradle, quality/checkstyle.xml, scripts/trigger-publishing.sh
This changeset pulls the changes from the recent `master` branch (at its state after 1.6.0 release) to the `2.x-jdk8-master` branch.
=> [2.x-jdk8] Absorb `config` at 1.6.0

scripts/publish-artifacts.sh
This changeset enables the publishing for the `2.x-jdk8-master` branches.
=> [2.x-jdk8] Enable artifact publishing

gradle/publish.gradle
When publishing an artifact, Spine's publishing routines determine the target repository basing on the version of the artifact.
The snapshot versions are published to the snapshot repository, the release versions go to the release repo.
Previously, only strings such as `1.6.10-SNAPSHOT+10` qualified as snapshot versions. This changeset updates the code to count versions like `2.0.0-jdk8.SNAPSHOT.4`  as snapshot versions as well.
=> [2.x-jdk8] Widen the definition of snapshot versions

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
We have the `defaultRepositories()` clause which configures the Maven repositories to search for libraries in.
Previously, we referenced only our Spine releases (besides all the default repos, such as `jCenter()`). And we were not using the Spine's snapshot repository.
This changeset appends the Spine snapshot repo to the list of the sources which are configured with the `defaultRepositories()` clause.
=> [2.x-jdk8] Add a reference to the snapshot repo

gradle/dart/pub-publish-tasks.gradle
`pub publish` command requires manual user approval. In order for it to pass, we provide the line "y" (as in "yes") to the `pub publish` process via standard input.
=> Provide "y" as input to `pub publish`

gradle/model-compiler.gradle
Since recent changes in Model Compiler, we no longer have to configure `columns { }` in Gradle. This PR removes the call to that deleted method from `model-compiler.gradle`.
=> Remove call to deleted method `columns`

gradle/model-compiler.gradle
Reverts SpineEventEngine/config#150
Turns out, we've got a separate branch for `2.x-jre8` branches.
=> Revert "Remove call to deleted method `columns`"

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/IncrementGuard.kt
In the spirit of gradually moving our CI infrastructure to GitHub, and, since we've disabled out PR Travis builds, we start running the `checkVersionIncrement` Gradle task on GitHub Actions.
The task is only enabled if the build is triggered by a `push` event to a non-master branch. Master branches end with "master". Now, in some repositories, there are two, `master` and `2.x-jdk8-master`.
=> Enable `IncrementGuard` on GitHub Actions

gradle/generate-pom.gradle
This PR extends the POM generation functionality with the newish Gradle scopes introduced in the latest versions. The change allows to better map Gradle to Maven scopes and is related to issue #156.
=> Add new scopes for POM generation

README.md, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/RunBuild.kt, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt, gradle/model-compiler.gradle, gradle/publish.gradle, pull, scripts/publish-artifacts.sh
This PR merges the changes from `2.x-jdk8-master` to `master`.
With this, we prepare for Spine release 2.0.
Migration to Java 11 is planned for later.
=> Start preparing 2.0

gradle/generate-pom.gradle
Fixes #170.
This PR fixes the POM generation process when there's a dependency with the same name and version.
This usually should not happen if the dependencies are forced and duplicates are excluded, but if not we may have such a situation when we're comparing the name and the version.
=> Fix the POM generation.

gradle/javac-args.gradle
This PR comments out `-Werror` Java compiler argument so that we don't fail a build in `base` when `config` changes.
See this issue (#173) for details.
=> Temporarily comment out `-Werror`

gradle/update-gh-pages.gradle
In this PR we allow the script which automatically updates the generated docs on GitHub Pages to make empty commits to the `gh-pages` branch.
Unless allowed explicitly, empty commits are an error in Git. However, for the purposes of our automatic system, we might want to make such commits. If, for example, nothing but infrastructural files are changed in a PR, or a successful `master` build is restarted, we don't want the build to fail just because the generated reference documentation has not changed.
=> Allow empty commits to `gh-pages`

gradle/javac-args.gradle
In this PR we disable the new `FloggerSplitLogStatement` ErrorProne warning.
Splitting Flogger statements is a conscious decision we've made for the sake of simpler logging API with `Logging`. This check will not prevent us from making a mistake. Instead, it is a nuisance.
=> Ignore a Flogger-related warning

gradle/buildSrc/build.gradle.kts, gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt, gradle/dependencies.gradle, gradle/jacoco.gradle, gradle/publish-proto.gradle, gradle/update-gh-pages.gradle
We're phasing out the usage of the JCenter Maven repository, replacing it with the conventional Maven Central. JCenter is announced to be shut down soon and is already experiencing deteriorated performance.
=> Phase out `jcenter()`

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt, gradle/publish.gradle
In this PR we allow to specify publishing credentials for a Maven repository via arguments, instead of a properties file.
We also define a preset for GitHub Packages publishing.
=> Maven repo credentials without a file

gradle/update-gh-pages.gradle
In this PR we remove the use of Travis specific env variables in the `update-gh-pages.gradle` script, so that we can update the docs from other CIs, namely, GitHub Actions.
=> Untie GitHub Pages publishing from Travis

gradle/jacoco.gradle
With the addition of Kotlin, source sets start having multiple output directories: one for Java and one for Kotlin.
This is not the only case for multiple output dirs, but this is the first one we happened to stumble upon.
In `jacoco.gradle` script, we treated `SoutceSet.output` as if it were a single path. We used `FileCollection.getAsPath()` for string representation. Once we added Kotlin, however, the method started to obtain a `PATH`-like string, which broke our build logic.
In this PR remove the erroneous use of `FileCollection.getAsPath()` and start processing `SoutceSet.output` paths one-by-one.
=> Fix JaCoCo herding

.gitattributes, gradle/jacoco.gradle
In this PR we fix a compilation error in `jacoco.gradle`.
We also update `.gitattributes` file with a new encryption file extension.
=> Fix error in JaCoCo script

gradle/buildSrc/src/main/kotlin/io/spine/gradle/internal/Publish.kt
In this PR we allow adding extra artifacts to the Maven publication. Previously, this ability was broken by a configuration error.
=> Allow extra artifacts

buildSrc/src/main/kotlin/io/spine/gradle/internal/Repositories.kt, buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt, quality/pmd.xml
This PR:
* Addresses warnings PMD emits on the rules that are going to be discontinued in the version 7.0. Rules were also sorted alphabetically for easier navigation.
* Deprecates `DependencyResolution.defaultRepositories()` method in favour of `applyStandard()` function (which now belongs to `Repositories.kt` file). The list of repositories stays the same.
=> Address PMD warnings

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/AppEngine.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/LicenseReport.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt, gradle/checkstyle.gradle, gradle/dependencies.gradle, gradle/license-report-project.gradle
This PR eliminates remaining string-based dependency usage in favor of those defined in Kotlin objects under `io.spine.internal.dependency` package.
The `version` property of the `deps` was removed to encourage using Maven coordinates declared in corresponding Kotlin objects.
Kotlin version was bumped to `1.5.0-RC`.
=> Use only Kotlin-defined dependencies

buildSrc/build.gradle.kts
This PR fixes the dependencies declared in `buildSrc/build.gradle.kts`. At this stage of a build, it is impossible to use imports or constants common for the `buildscript` and `plugin` clauses.
=> Fix bootstrap dependencies

buildSrc/src/main/kotlin/io/spine/internal/gradle/Scripts.kt
This PR opens `Scripts.commonPath` property to be used from Groovy-based scripts.
=> Open common path

buildSrc/build.gradle.kts, buildSrc/src/main/groovy/dependencies.gradle
This PR:
* Fixes paths to dependency objects using fully-qualified names (because imports in Groovy are not stable when working with IDEA).
* Adds `groovy` plugin to `buildSrc` build script. This, again, makes it it more reliable in IDEA.
=> Fix paths to Kotlin objects

buildSrc/src/main/kotlin/io/spine/internal/dependency/JUnit.kt
In this PR we add the `org.junit.jupiter:junit-jupiter-params` artifact to be used as a dependency.
=> Add JUnit params dependency

buildSrc/src/main/groovy/dart/build-tasks.gradle, buildSrc/src/main/groovy/dart/pub-publish-tasks.gradle
In Groovy Gradle scripts, declaring a package is a compile-time error.
=> Remove packages in Gradle scripts

buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
This PR adds the gRPC Protobuf plugin artifact to the `Grpc` object.
Also, updates the versions of Protobuf, gPRC, and the Protobuf Gradle plugin.
=> Update versions and add gRPC plugin

buildSrc/src/main/groovy/update-gh-pages.gradle
Before this changeset, each build from `master` published its updates to the Javadoc-only branch called `gh-pages`.
As a result, [spine.io](https://spine.io) readers would see the Javadocs of some `...-SNAPSHOT.42` instead of the documentation for the latest release.
This PR disables the corresponding Gradle task for snapshots.
=> Disable publishing Javadocs to GitHub Pages for snapshots

buildSrc/src/main/kotlin/io/spine/internal/dependency/Truth.kt
Updates Google Truth so that the issue with required fields and `comparingExpectedFieldsOnly()` is resolved.
In past versions, this assertion mode failed if a Proto 2 required field was not set. This was a problem for us as we use the same validation sites for Spine validation as does Proto 2 for their inbuilt validation.
=> Update Google Truth version

buildSrc/src/main/kotlin/io/spine/internal/dependency/AnimalSniffer.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt
In this PR we add the Dokka Gradle plugin artifact coordinates.
Note that Dokka uses a different version from Kotlin.
We also remove a doc copied by error in `AnimalSniffer.kt`.
=> Dokka plugin dependency

.idea/inspectionProfiles/Project_Default.xml
We turn off the warning which reports methods that override annotated `@NonNull` methods but are not annotated by themselves.
This warning is triggered when a Java method overrides a Kotlin method, since Kotlin methods are annotated with the JetBrains' `@Nonnull`. We don't use JetBrains annotations in our code.
=> Turn off `null` inheritance warning

buildSrc/src/main/kotlin/io/spine/internal/gradle/RunBuild.kt
In this PR we introduce the ability for the `RunBuild` task to copy Gradle properties from the current build into the build launched by `RunBuild`.
=> Copy properties in `RunBuild`

buildSrc/src/main/kotlin/io/spine/internal/gradle/RunBuild.kt
Now we print the error output of a Gradle build that was launched via `RunBuild` instead of just giving the file name.
=> Print error message if an included build fails

buildSrc/src/main/kotlin/force-jacoco.gradle.kts
This PR adds a temporary script for bypassing a JaCoCo issue by forcing the latest version.
See [this issue](https://github.com/SpineEventEngine/config/issues/214) for more info.
=> Force JaCoCo

buildSrc/src/main/groovy/license-report-project.gradle
This PR makes the method `getFileNameCache()` of `MarkdownReportRenderer` `public` because this is a requirement of Gradle 7.x for getters annotated with `@Input`.
=> Make `@Input` public

buildSrc/src/main/kotlin/io/spine/internal/dependency/Jackson.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Roaster.kt
In this PR we
1. Add a dependency for Jackson YAML parsing components.
2. Update versions:
- Jackson: `2.12.3` to `2.12.4`;
- Kotlin: `1.5.0` to `1.5.20`;
- Dokka: `1.4.32` to `1.5.0`;
- Protobuf: `3.17.0` to `3.17.3`;
- Roaster: `2.22.0.Final` to `2.23.0.Final`.
=> Jackson YAML parsing and version bumps

buildSrc/src/main/kotlin/io/spine/internal/dependency/Jackson.kt
In this PR we add the Jackson module for Kotlin interop.
The module enables Jackson to work with Kotlin data classes.
=> Add Jackson Kotlin module

buildSrc/src/main/kotlin/io/spine/internal/dependency/Roaster.kt
This PR rolls the version of Roaster back to `2.22.2.Final` to restore compatibility with Java 8.
Please see #220 for details.
=> Roll back Roaster to the version compatible with Java 8

buildSrc/src/main/groovy/run-build.gradle, buildSrc/src/main/kotlin/io/spine/internal/gradle/RunBuild.kt
This PR allows reasonably long (10 minutes) timeout for waiting for a build process initiated by a Gradle script.
This is done to overcome the issue with stalled child processes under Windows.  See the following locations for details:
* https://github.com/gradle/gradle/pull/8467#issuecomment-498374289
* https://github.com/gradle/gradle/issues/3987
* https://discuss.gradle.org/t/weirdness-in-gradle-exec-on-windows/13660/6
=> Allow timeouts for processed initiated from Gradle under Windows

buildSrc/src/main/kotlin/io/spine/internal/gradle/RunBuild.kt
This PR improves the `RunBuild` task by:
* adding `--no-daemons` flag to ease the child process issue under Windows;
* improving error diagnostics when a process exit code is not zero.
=> No daemons running build

buildSrc/src/main/kotlin/io/spine/internal/dependency/ErrorProne.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Pmd.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/Publish.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/Scripts.kt, buildSrc/src/main/kotlin/pmd-settings.gradle.kts, buildSrc/src/main/resources/pmd.xml
This PR introduces a script plugin for configuring PMD. 
Before this PR, PMD was configured using a Groovy-based script (see `buildSrc/src/main/groovy/pmd.gradle`).
This script applies the settings stored in the file under the sub-directory of `config` (see `quality/pmd.xml`). A script is applied in a build file like this:
```kotlin
apply {
with(Scripts) {
from(pmd(project))
}
}
```
It works when this code is in a `subprojects` closure of a build script. But if it's applied to a separate project (in a sub-directory), this code breaks because the reference to `config/quality/pmd.xml` used by the Groovy-based script no longer works.
After this PR, a PMD could be configured using this code:
```
plugins {
`pmd-settings`
}
```
The XML file is the script plugin uses is placed under …
=> Script plugin for PMD settings

.idea/codeStyles/Project.xml, buildSrc/src/main/resources/pmd.xml
This PR:
* Removes PMD rules `UnusedImports` and `DontImportJavaLang`  (from the `resources/pmd.xml` file) as they were deprecated and scheduled for removal in PMD 7.0.0.
* Updates Protobuf code style to have indents of 4 spaces (instead of 2).
=> Remove deprecated PMD rules

buildSrc/src/main/kotlin/io/spine/internal/gradle/Publish.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/RunBuild.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/RunGradle.kt
This PR extends the `Publish` (aka `spinePublishing`) with the ability to publish a single-module project.
The changes look vast because private extension functions were pushed to the file level to reduce code nesting.
=> Allow publishing of single-module projects

buildSrc/src/main/kotlin/io/spine/internal/gradle/DependencyResolution.kt
This PR forces the version of `ErrorProne.core` dependency.
=> Force `ErrorProne.core`

buildSrc/src/main/kotlin/io/spine/internal/gradle/Publish.kt
This PR fixes the issue of checking the publishing mode by moving the code under `Project.afterEvaluate`
=> Fix publishing

buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
Previously, GitHub Packages could not be used as a source for dependencies. 
This changeset enables that, making the recently introduced `base-types` — which is only published to GitHub Packages — available to `core` modules.
In future PRs, it is planned to simplify the API and get rid of nasty `project` variable required to read the ausweis.
=> Allow to fetch dependencies from GitHub Packages

buildSrc/build.gradle.kts, buildSrc/src/main/groovy/license-report-project.gradle, buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
In this PR we configure publishing artifacts to and fetching artifacts from the Google Cloud Artifact Registry.
The registry hosts a Maven repo which serves Java artifacts.
Unlike GitHub Packages, Google CAR allows public auth-free access to the artifacts.
Right now, two repositories are created, one for releases and one for snapshots.
In order to fetch the artifacts, consumers would only need to plack the right URL into their build script:
```kotlin
repositories {
maven {
url = uri("https://europe-maven.pkg.dev/spine-event-engine/releases")
}
maven {
url = uri("https://europe-maven.pkg.dev/spine-event-engine/snapshots")
}
}
```
Alternatively, just use `applyStandard()` to use the standard Spine repositories, which include the Google CAR repositories.
In order to publish artifacts, the …
=> Google Cloud Artifact Registry publishing

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/gradle/Clean.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/ConfigTester.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/GitCheckout.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/RunGradle.kt, scripts/update-apt.sh
Previously, any changes made to `config` may turn out to be breaking for some of Spine repositories. The main reason for that was the cost of testing, which required manual checkout of all repos, copying the `config` and `buildSrc` over to them, and launching builds.
This changeset adds a `ConfigTester` to automate all that. This tool serves to probe the Spine repositories for compatibility with the local changes in the `config` repository. Long story short, that's how one uses it (copied from `config/build.gradle.kts`):
```kotlin
// A reference to `config` to use along with the `ConfigTester`.
val config = Paths.get("./")
// A temp folder to use to checkout the sources of other repositories with the `ConfigTester`.
val tempFolder = File("./tmp")
// Creates a Gradle task which checks out …
```
=> Allow to test `config` and `config/buildSrc` with local modifications with existing Spine repositories

buildSrc/src/main/kotlin/io/spine/internal/gradle/CheckVersionIncrement.kt
Previously, `checkVersionIncrement` task has been targeting only `releases`. So, release versions could not be overwritten once they had been published. It was still possible to overwrite snapshots.
However, as we started publishing to GitHub Packages, any overwrites became impossible. An attempt to do so now resolves in a HTTP response 409 "Conflict".
This changeset now forces the check to ensure neither of `snapshots` and `releases` repositories contains the version which is to be published.
Please note, that for local builds AND for the CI runs in `master` branches this task will still NOT run. It is a precautious measure, partially explained by the comment in `IncrementGuard`:
```kotlin
/**
* Adds the [CheckVersionIncrement] task to the project.
*
* Only adds the check if the project …
```
=> Run `checkVersionIncrement` for both `releases` and `snapshots`

buildSrc/build.gradle.kts, buildSrc/src/main/groovy/license-report-project.gradle
This PR:
* Extracts artifact prefix calculation used in `license-report-project.gradle`.
* Removes unnecessary usage of Spring Maven repository.
=> Clarify artifact prefix calculation

.codecov.yml, pull
This PR:
* Enables Codecov patch statuses in the default configuration (to avoid the confusion when initialized in a new repo).
* Tunes the `pull` script to not overwrite already present configuration files in the root directory of the project.
=> Tune copying

buildSrc/src/main/kotlin/io/spine/internal/gradle/Clean.kt
This PR cleans the `Clean.kt` from a redundant semicolon and unused import.
=> Remove redundant semicolon

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
In this PR we advance the version of the GCAR cloud library, which fixes the issue with uploading large atrifacts.
This fix allows us, finally, to publish into the GCAR.
=> Return of the Google Cloud Artifact Registry

buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
Somehow, we called the properties that store GCAR URLs `cloudArchive` and `cloudArchiveSnapshots`.
Google Cloud Artifact Registry is not a cloud archive. Indeed, Cloud Archive is a name of an Azure service.
In this PR we correct that mistake.
=> Fix a typo

buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/VersionWriter.kt
In this PR we introduce `VersionWriter`, a `buildSrc` Gradle plugin that generates a `.properties` file with artifact versions in it. The file is included into the project's JAR.
This is a common routine in our Gradle plugins. Now that we split the plugins into multiple repositories, it's nice to have this part shared via `config` instead of copying it over many Git repos.
Also, in this PR, we update the Protobuf version to `3.18.0`.
=> Version writer

.github-workflows/ensure-reports.updated.yml, scripts/ensure-reports-updated.sh
Previously, it was possible to forget that the license report files in Spine libraries had to be updated in accordance with the new versions and-or dependencies. So some PRs could be merged without these changes in place.
This PR adds a GitHub Actions workflow to ensure that the license report files are modified within the PR.
=> Add a workflow to ensure the license report files are updated

README.md, buildSrc/src/main/kotlin/travis-warnings.gradle.kt
This PR introduces a Gradle script plugin for configuring logging of `javadoc` tasks when running under Travis. 
Even though, we're stopping using Travis, this piece of knowledge is valuable, and should be preserved before we remove it from build scripts.
=> Travis-specific Javadoc task log configuration

.github-workflows/build-on-ubuntu.yml
We remove the `# optional (default = false)` comments from the `build-on-ubuntu.yml`. This comment was copied from the action usage example and has no value for us.
=> Clean up a workflow file

buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt
This PR moves the `Dokka` dependency object to the package level. Previously, it was under `Kotlin`. 
Since Dokka is versioned differently than Kotlin, having it as a top level dependency object makes more sense.
=> Pull Dokka to the package level

buildSrc/src/main/kotlin/io/spine/internal/gradle/ProjectExtensions.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/Publish.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/VersionWriter.kt
In this PR we fix the `VersionWriter` so that the generated file is added automatically to the resources.
=> Fix `VersionWriter`

pull
When pulling changes from `config`, sometimes, new files are added to the `buildSrc` Gradle project.
The users have to add those files to Git manually.
In this PR we make the `pull` script add new source files of the `buildSrc` Gradle project to Git automatically.
=> Add `buildSrc/src`  to Git after `pull`

buildSrc/src/main/groovy/license-report-project.gradle, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/ProjectExtensions.kt
This PR fixes the reference to the new publishing API made from the `license-report-project.gradle` script.
=> Fix import in `license-report-project.gradle`

buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/JavadocConfig.kt
This PR adds properties to the `Grpc` dependency object which are used in `gcloud-java`. Even though there's only one repository now, it would be better to have these properties to highlight their usage, and ease the search.
Also this PR enforces UTF-8 encoding when applying the `JavadocConfig` plugin to a Gradle project.
=> Extend gRPC dependencies

buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/UpdateGitHubPages.kt
This changeset updates the `updateGitHubPages` Gradle task.
Previously, it was skipping all the actions in case the project was a `SNAPSHOT`. However, it led to some issues, as consuming Gradle projects may have had a dependency onto `updateGitHubPages` — whether it was actually registered or not.
Now, we always register `updateGitHubPages` as a Gradle task. But for `SNAPSHOT` projects, it just prints a diagnostic message telling that the actual update is going to be skipped for the `SNAPSHOT`-versioned project.
=> Smarter `updateGitHubPages` task

buildSrc/src/main/groovy/license-report-repo.gradle
Previously, the `license-report-repo.gradle` was not able to handle the repositories consisting of just a single project.
This changeset addresses this flaw.
=> Adjust the license report script for solo-project repos

buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/UpdateGitHubPages.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/UpdateGitHubPagesExtension.kt
This changeset introduces a way to include some external inputs into the GitHub Pages update.
```kotlin
updateGitHubPages {
// ...
// A directory, or a path to the directory.
includeInputs.add(someDir)
// Or, an output of some task.
includeInputs.add(anotherTask)
}
```
The values are treated according to the specification of [Copy.from](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/AbstractCopyTask.html#from-java.lang.Object...-), which, in turn, delegates the evaluation to [Project.files](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#files-java.lang.Object...-).
=> Allow external inputs for `UpdateGitHubPages`

buildSrc/src/main/groovy/js/build-tasks.gradle, buildSrc/src/main/groovy/js/configure-proto.gradle, buildSrc/src/main/groovy/js/js.gradle, buildSrc/src/main/groovy/js/npm-cli.gradle, buildSrc/src/main/groovy/js/npm-publish-tasks.gradle, buildSrc/src/main/groovy/js/update-package-version.gradle, buildSrc/src/main/kotlin/io/spine/internal/dependency/GoogleApis.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/GoogleCloud.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/HttpClient.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/J2ObjC.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/JavaX.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Netty.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/OsDetector.kt
This PR adds and improves dependency objects that are used in `web` and `gcloud` sub-projects.
Also, import statements in `js/*.gradle` scripts were inlined to remove the references to the `deps` property.
=> Improve dependency objects

buildSrc/src/main/groovy/js/build-tasks.gradle, buildSrc/src/main/groovy/js/js.gradle, buildSrc/src/main/groovy/js/npm-publish-tasks.gradle, buildSrc/src/main/kotlin/io/spine/internal/dependency/CommonsLogging.kt
This PR fixes paths used in the `gradle/js` folder.
Also, documentation for `CommonsLogging` dependency object was improved.
=> Fix script plugin paths in `js`

buildSrc/build.gradle.kts
For some reason, we declared the license report plugin twice: in `buildscript { }` and in `plugins { }`.
Now we only do that in `plugins { }`.
=> Remove redundant plugin dependency

buildSrc/src/main/groovy/jacoco.gradle, buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/UpdateGitHubPages.kt
This PR:
* Fixes `UpdateGitHubPages` so that it does not use `ExcludeInternalDoclet` when no Javadoc filtering of `@Internal` API is needed.
* Removes `evaluationDependsOnChildren()` on children call in `jacoco.gradle` script because it conflicts with Maven publishing. See [this discussion](https://discuss.gradle.org/t/gradle-7-fails-with-cannot-run-project-afterevaluate-action-when-the-project-is-already-evaluated/40296) for details.
=> Fix Javadoc filtering and `jacoco` forceful evaluation of child projects

.idea/inspectionProfiles/Project_Default.xml, buildSrc/src/main/kotlin/io/spine/internal/gradle/ProjectExtensions.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/VersionWriter.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Publish.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/PublishExtension.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/PublishingExtensions.kt
This PR standardizes the way we treat module names when writing `versions-*.properties` files. Previously, these files were composed using module names of a Gradle project. 
In most of the sub-projects, we also add `spine-` prefix when publishing to Maven (using `spinePublishing/spinePrefix` property). Not taking in account the prefix resulted in the confusion:
* When adding dependencies in a project, we need to take the prefix into account.
* But whey they are loaded from the code (when reading `.properties`) we had to “remember” somehow if the artifact had the `spine-` prefix or not.
After this PR, we always Maven artifact ID.
=> Use Maven artifact ID for version files

buildSrc/build.gradle.kts, buildSrc/src/main/groovy/javac-args.gradle, buildSrc/src/main/kotlin/io/spine/internal/dependency/ErrorProne.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/javac/ErrorProne.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/javac/Javac.kt
This changeset migrates `javac-args.gradle`  to Kotlin.
The original script was split into two: 
1. `Javac.kt` - configures java compilation aspects;
2. `ErrorProne.kt` - configures ErrorProne.
```
// old API
with(Scripts) {
from(javacArgs(project))
}
// new API
tasks {
withType<JavaCompile> {
configureErrorProne()
configureJavac()
}
}
```
`ErrorProne Gradle Plugin` was added on a buildSrc classpath to have `ErrorProne.kt` typed. Thus, it'd be on a classpath of each build file and no version should be specified in `plugins.apply` block. Old scripts that specify version would fail.
```
// old API
io.spine.internal.dependency.ErrorProne.GradlePlugin.apply {
id(id) version version
}
// new API
io.spine.internal.dependency.ErrorProne.GradlePlugin.apply {
id(id)
}
```
=> Migrate `javac-args.gradle` to Kotlin

buildSrc/src/main/groovy/slow-tests.gradle, buildSrc/src/main/groovy/test-output.gradle, buildSrc/src/main/kotlin/io/spine/internal/gradle/test/Logging.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/test/Tasks.kt
This changeset migrates `slow-tests.gradle` and `test-output.gradle` to Kotlin.
`slow-tests.gradle` was migrated to `test/Tasks.kt`:
```
// old API
apply {
with(Scripts) {
from(slowTests(project))
}
}
// new API
tasks {
registerTestTasks()
}
```
`test-output.gradle` was migrated to `test/Logging.kt`:
```
// old API
apply {
with(Scripts) {
from(testOutput(project))
}
}
// new API
tasks {
withType<Test> {
configureLogging()
}
}
```
=> Migrate `slow-tests.gradle` and `test-output.gradle` to Kotlin

buildSrc/src/main/groovy/test-artifacts.gradle, buildSrc/src/main/kotlin/io/spine/internal/gradle/testing/Artifacts.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/testing/Logging.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/testing/Tasks.kt
This changeset migrates `test-artifacts.gradle` to Kotlin.
```
// old API
apply(
from = Scripts.testArtifacts(project)
)
// new API
java {
exposeTestArtifacts()
}
```
Also, package `kotlin/.../test` was renamed to `kotlin/.../testing`. The reason is that `test` usually means the package with tests. This is clearly not the case for us.
=> Migrate `test-artifacts.gradle` to Kotlin

buildSrc/src/main/groovy/slow-tests.gradle, buildSrc/src/main/kotlin/io/spine/internal/gradle/testing/Tasks.kt
This PR fixes deprecation message in `slow-tests.gradle` to correctly name the receiver type of `registerTestTasks()` extension function.
Also, this PR fixes KDoc links to types that are not available via fully-qualified references.
=> Fix deprecation message

pull
This PR removes earlier added `-u` option for `cp` because the option is not available under macOS.
=> Avoid `u` option when copying files in `pull`

.idea/inspectionProfiles/Project_Default.xml, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Jackson.kt
This PR:
* Relaxes IDEA inspection for test class names to NOT require the `Test` suffix.
* Bumps Jackson -> 2.13.0.
=> Relax test names inspections and bump Jackson

.github-workflows/build-on-windows.yml
The post run for `setup-java@v2` under Windows fails with the following console output:
```
Post job cleanup.
C:\Windows\System32\tar.exe --posix -z -cf cache.tgz -P -C D:/a/tool-base/tool-base --files-from manifest.txt
tar.exe: Couldn't open C:/Users/runneradmin/.gradle/caches/modules-2/modules-2.lock: Permission denied
tar.exe: Error exit delayed from previous errors.
Warning: Failed to save Gradle cache on Windows. If tar.exe reported "Permission denied", try to run Gradle with `--no-daemon` option. Refer to https://github.com/actions/cache/issues/454 for details.
Warning: Error: Tar failed with error: The process 'C:\Windows\System32\tar.exe' failed with exit code 1
```
This PR instructs Gradle build to run with `--no-daemon` flag.
Please see …
=> Run Gradle in `no-daemon` mode

buildSrc/src/main/kotlin/io/spine/internal/gradle/checkstyle/CheckStyleConfig.kt, quality/checkstyle.xml
This changeset addresses the current misconfiguration of Checkstyle plugin. The current version starts to crash when building Spine with JDK 11.
Now, we use a proper approach to define the `config` folder location.
=> Checkstyle: set the `config` directory properly

buildSrc/src/main/kotlin/io/spine/internal/gradle/StringExtensions.kt
We add the name of the optional argument of a method used in the `isSnapshot()` extension method to make it more readable.
=> Make `String.isSnapshot()` more readable

buildSrc/src/main/kotlin/io/spine/internal/dependency/CheckStyle.kt
Previously, we were using `8.29`. Now, it's `9.1`.
=> Update CheckStyle plugin to the most recent version

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/javac/Javac.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/kotlin/KotlinConfig.kt
This PR:
* Bumps Kotlin version to 1.6.0.
* Sets the version of Kotlin Gradle plugin under `buildSrc`.
* Adds extension function for `KotlinCompile` for setting commonly used free compiler args.
* Adds extension for setting Kotlin JVM toolchain (which also [selects](https://kotlinlang.org/docs/gradle.html#gradle-java-toolchains-support) corresponding Java version).
=> Kotlin configuration

buildSrc/src/main/kotlin/io/spine/internal/gradle/kotlin/KotlinConfig.kt
This PR fixes imports that were accidentally removed in `KotlinConfig.kt`.
=> Fix  missing imports

.idea/codeStyles/Project.xml
That would help unifying the formatting of the code chains.
=> Add `singleTenant` and `multitenant` to the list of builder methods

.github-workflows/build-on-ubuntu.yml, .github-workflows/build-on-windows.yml, .github-workflows/increment-guard.yml, .github-workflows/publish.yml, .idea/kotlinc.xml, .idea/misc.xml, buildSrc/src/main/kotlin/io/spine/internal/gradle/javac/Javac.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/kotlin/KotlinConfig.kt
This PR sets Java 11 when running GitHub Workflows and in IDEA settings.
Other changes:
* The `publish` workflow now does not run tests. There's no need to do that since the workflow is associated with the `master` branch, which means tests in a PR passed.
* Added `String` parameter overload for `KotlinJvmProjectExtension.applyJvmToolchain()`. There was only `Int` version which felt a bit awkward in combination with Java version constants from Gradle.
=> JDK 11 and no tests when publishing

buildSrc/src/main/groovy/dart/build-tasks.gradle, buildSrc/src/main/groovy/dart/pub-publish-tasks.gradle, buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/DartContext.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/DartEnvironment.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/DartExtension.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/plugin/DartPlugins.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/plugin/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/task/Build.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/task/DartTasks.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/task/IntegrationTest.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/task/Publish.kt
This changeset migrates `buildSrc/.../groovy/dart/*` package to Kotlin:
1.  `build-tasks.groovy` was migrated to `DartTasks.build()`.
2. `pub-publish-tasks.gradle` was migrated to `DartTasks.publish()`.
Here's an example of how to use it in a project's `build.gradle.kts`:
```
// old API
apply {
from(Deps.scripts.dartBuildTasks(project))
from(Deps.scripts.pubPublishTasks(project))
}
// new API
dart {
tasks {
build()
publish()
}
}
```
Additionally, this PR extracts configuration of `protobuf` plugin and `integrationTest` task into `buildSrc`.
Here's an example of how to use it in a project's `build.gradle.kts`:
```
// old API
val integrationTestDir = "./integration-test"
val integrationTest by tasks.creating(Exec::class) {
// ...
}
protoDart { …
```
=> Migrate `buildSrc/.../groovy/dart/*` scripts to Kotlin

.idea/inspectionProfiles/Project_Default.xml
This changeset configures IDEA to treat all explicit variable types as warnings.
=> Promote using `var` in IDEA

.lift.toml, pull
We add the Sonatype Lift configuration file and suppress Detekt's `SpeadOperator` warning.
As the Lift uses an old version of Detekt, [this bug](https://github.com/detekt/detekt/issues/3145) causes false alarm on any spread operator usage in Kotlin.
For now, we turn the check off. Later, we should re-enable it, once Lift upgrades the Detekt version.
=> Suppress `SpeadOperator` warning

README.md, buildSrc/src/main/kotlin/io/spine/internal/dependency/Guava.kt, gradle/wrapper/gradle-wrapper.properties
This PR:
* Bumps Gradle -> `7.3.2`
* Bumps Guava -> `31.0.1-jre`
* Removes the link to a Travis doc in readme.
=> Bump Gradle and Gradle

buildSrc/src/main/kotlin/io/spine/internal/dependency/Flogger.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/JUnit.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt
This PR bumps versions:
* Kotlin -> 1.6.1
* Flogger -> 0.7.3
* JUnit -> 5.8.2; API Guardian -> 1.1.2; JUnit Pioneer -> 1.5.0
=> Bump Kotlin, Flogger, and JUnit

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt
This PR fixes trailing zero in `1.6.10` of Kotlin and syncs versions in `build.gradle.kts` with those recently changed under `dependency` package.
=> Fix trailing zero in Kotlin version

buildSrc/src/main/kotlin/io/spine/internal/dependency/J2ObjC.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/DependencyResolution.kt
This PR rolls back the version of J2ObjC from `1.3.1` to `1.3`, which is the latest version available from Maven Central.
The artifact we use is `j2objc-annotations` and this PR deprecates the `lib` property in favor of a new one called `annotations`, which clarifies the nature of the dependency.
=> Rollback J2ObjC version to 1.3.

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
This PR advances the version of Protobuf Gradle Plugin.
=> Bump Protobuf Gradle Plugin -> `0.8.18`

buildSrc/src/main/kotlin/io/spine/internal/dependency/Apache.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ApacheHttp.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/CommonsCodec.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/GoogleCloud.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt
This PR advances versions of Google Cloud libraries and adds Apache Commons dependency. 
`GoogleApis.AuthLibrary.oAuth2Http` and `Grpc.auth` libs were moved from the `api` configuration of the latest `google-cloud-trace` library. Modules that used those libraries transitively, now should link them explicitly and force the versions if conflicts occur:
```
dependencies {
api(GoogleCloud.trace)
testImplementation(GoogleApis.AuthLibrary.oAuth2Http)
testImplementation(Grpc.auth)
}
configurations {
all {
resolutionStrategy {
force(
ApacheHttp.core,
CommonsCodec.lib,
Grpc.auth,
GoogleApis.AuthLibrary.credentials
)
}
}
}
```
=> Bump versions of Google Cloud libraries

buildSrc/src/main/kotlin/io/spine/internal/dependency/HttpClient.kt
This PR adds `apache2` implementation of Google Http Java Client. This is used to force version.
=> Add `google-http-client-apache-v2` dependency

buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
This PR bumps the version of Protobuf, addressing the [security vulnerability](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22569) recently reported by [OSS-Fuzz](https://github.com/google/oss-fuzz).
Also, the `protobuf-kotlin` artifact was added to the list of Protobuf `libs` we use to ease the adoption of Kotlin Protobuf DSL.
=> Bump Protobuf version -> `3.19.2`, add `protobuf-kotlin`

buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/CheckVersionIncrement.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/IncrementGuard.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/PublishExtension.kt
This PR:
* Consolidates script plugins related to publishing under the `io.spine.gradle.publish` package.
* Adds an ability to set a `customPrefix` value when doing `spinePublishing`.
* Bumps Protobuf -> `3.19.3`.
=> Custom artifact prefix

.github-workflows/build-on-ubuntu.yml, .github-workflows/build-on-windows.yml, buildSrc/build.gradle.kts
This PR:
* Advances the version of License Report used in `buildSrc` to version `2.1`.
* Adds [publishing of test reports](https://github.com/marketplace/actions/junit-report-action) to build workflows under Ubuntu and Windows.
=> Bump License Report, publish test reports

buildSrc/src/main/kotlin/io/spine/internal/dependency/KotlinSemver.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/proto/ProtoLocators.kt
This PR adds the dependency object of [`kotlin-semver`](https://github.com/z4kn4fein/kotlin-semver) library.
=> Add `kotlin-semver` dependency

buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Artifacts.kt
This PR extract non-declarative code from `base`'s build file.
The extracted code excludes Google `.proto` files from all artifacts.
An example of how to use it:
```
tasks {
excludeGoogleProtoFromArtifacts()
}
```
=> Add possibility to exclude Google `.proto` files from artifacts

buildSrc/src/main/kotlin/io/spine/internal/dependency/TestKitTruth.kt
This PR adds dependency object for [TestKit Truth](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/tree/main/testkit-truth).
The usage of this Truth extension is described in [this article](https://dev.to/autonomousapps/gradle-all-the-way-down-testing-your-gradle-plugin-with-gradle-testkit-2hmc).
=> Add `testkit-truth` dependency

buildSrc/src/main/kotlin/io/spine/internal/gradle/VersionWriter.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Artifacts.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/MavenJavaPublication.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/ProtoJar.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/ProtoLocators.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/PublishingConfig.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/SpinePublishing.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Tasks.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/TestJar.kt
This changeset removes `testJar` from the list of artifacts that are published by default. Publishing of this artifact is optional now and can be enabled via `SpinePublishing.testJar` method.
In addition to that, the PR does the following refactoring:
1. Renames `testOutputJar` task to just `testJar`. Each task within `Artifacts.kt` has a name that matches to pattern `<archive classifier>Jar`. This one was an exception.
2. Extracts `ProtoJar` DSL element for `SpinePublishing` into a separate file.
3. Makes `spinePublishing` not append a hyphen to `artifactPrefix`.
4. Drops usages of `Collection` when it is not required by a domain.
=> Make publishing of `testJar` artifact optional

buildSrc/src/main/kotlin/io/spine/internal/gradle/testing/Multiproject.kt
This changeset renames `exposeTestArtifacts()` in order not to clash with artifacts that are published to Maven.
As for now It is possible to expose the test classes in two ways:
1. With `exposeTestArtifacts() -> exposeTestConfiguration()` as a consumable Gradle configuration. Such exposure works only within a Gradle multi-project build. One subproject exposes its test classes to other subprojects. 
2. With `SpinePublishing.testJar` artifact. The test classes are packed into a jar archive in a form of compiled classes. This archive is published to a Maven repository and then can be consumed by external projects.
=> Rename `exposeTestArtifacts` to `exposeTestConfiguration`

gradle/wrapper/gradle-wrapper.properties
This PR advances the version of Gradle we use to [`7.4.2`](https://docs.gradle.org/current/release-notes.html).
=> Bump Gradle -> `7.4.2`

buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/SpinePublishing.kt
There are several places where `spinePublishing` can be opened:
1. In a root project to configure publishing of:
1.1. subprojects.
1.2. a root project itself.
2. In a subproject to configure publishing of a subproject itself.
Case (1.2) didn't work. The build failed. This PR fixes this.
=> Enable `spinePublishing` publish a root project itself

buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt
This PR advances the version of Dokka we use to [`1.6.10`](https://github.com/Kotlin/dokka/releases/tag/v1.6.10).
=> Bump Dokka -> `1.6.10`

buildSrc/src/main/kotlin/io/spine/internal/dependency/Jackson.kt, scripts/compare-dirs.sh
This PR:
* Advances the version of Jackson dependencies to fix CWE-787 security vulnerability.
* Adds a Bash script for comparing content of two directories.
=> Bump Jackson -> `2.13.2.1`

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt
This PR advances the version of Dokka we use to [`1.6.20`](https://github.com/Kotlin/dokka/releases/tag/v1.6.20).
=> Bump Dokka -> `1.6.20`

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt
This PR finishes bumping the Kotlin version to `1.6.20`, started in [this PR](https://github.com/SpineEventEngine/config/pull/354). Also, a reminder-comment was added to keep versions in sync across multiple places.
=> Finish bumping Kotlin

buildSrc/src/main/kotlin/dokka-for-java.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/dokka/DokkaExtensions.kt
[The PR](https://github.com/SpineEventEngine/config/pull/352) which extended our Dokka support did not fully cover all edge-cases of generating documentation. One was found during generating documentation for a multi-language project with both Java and Kotlin source files. Currently, Dokka does not allow a clear and concise way to generate documentation for both Java+Kotlin projects. You are either "seeing Java code as Kotlin" or vice versa. Now we are sticking to generating documentation for Java code. This PR is fixing the described issue by considering only Java source files when generating Dokka documentation via `dokka-for-java` script plugin. Also, this PR bumps `spine-dokka-extensions`.
=> Fix Dokka documentation for Kotlin+Java projects

buildSrc/src/main/kotlin/io/spine/internal/gradle/kotlin/KotlinConfig.kt
This PR:
1. Adds Kotlin compiler flags that were recently used in ProtoData.
2. Removes the `X` prefix before `-opt-in`, thus avoiding the warning issued since Kotlin version `1.6.20`.
=> Tune Kotlin compiler flags

buildSrc/src/main/kotlin/io/spine/internal/gradle/report/pom/DependencyWriter.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/report/pom/ModuleDependency.kt
This PR addresses #362.
As described in the issue, sometimes we can't overcome the presence of several versions of the same dependency. `pom.xml` is generated upon a whole project and doesn't group dependencies by modules. Specific modules override versions dictated by `config`. And, as a result, several versions of the same dependency leak to `pom.xml`.
`spine-time` repository is an example here. Each subproject is configured to use a specific version of `protoc` from `config`. The configuration is performed from the root project:
```
protoc {
artifact = Protobuf.compiler
}
```
Meanwhile, `time` module applies our `mc-java` plugin, and not the last version. The plugin overrides the version of `protoc`, specified by the root. As a result, the module uses its own version.
---
This PR makes …
=> Filter out duplicated dependencies from `pom.xml`

buildSrc/src/main/kotlin/io/spine/internal/dependency/Jackson.kt
Applying Dokka in `web` repository requires forcing of two more Jackson dependencies.
This PR adds the following dependencies:
1. `jackson-bom`.
2. `jackson-annotations`.
=> Add more Jackson dependencies

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/RunGradle.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/protobuf/ProtoTaskExtensions.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/GitHubPackages.kt, buildSrc/src/main/kotlin/write-manifest.gradle.kts
This PR adds storing of necessary attributes is done by the script plugin `write-manifest.gradle.kts` which should be applied to each subproject which needs version information. It was previously [introduced in `tool-base`](https://github.com/SpineEventEngine/tool-base/pull/21).
It also brings stability improvements for running under Windows:
* `GitHubPackages.kt` was modified to extract the ZIP archive using the [zip4j](https://github.com/srikanth-lingala/zip4j) library, instead of using `unzip` command line utility which is not available in vanilla Windows.
* `RunGradle.kt` was modified to use the `_out` directory instead of `build`. Using `build` for debug output of processes created by `ProcessBuilder` failed the `clean` command under Windows because of files already opened in the …
=> Write manifests and improvements for Windows

buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/DependencyResolution.kt
This PR enforces the version of the `jackson`-related dependencies. Dokka is dependent on [`jackson-databind@2.12.4`](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.12.4), which has a critical vulnerability. To avoid this vulnerability the version is forced to the `2.13.2.2` for `jackson-databind` and to the `2.13.2` for all other `jackson`-related dependencies.
Also, the `Dokka.CorePlugin` dependency object was created. The dependency is used in `dokka-tools`, but it does not have a typed wrapper.
=> Force Jackson dependencies

buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt
This PR bumps `spine-dokka-extensions` to `2.0.0-SNAPSHOT.4`.
=> Bump `spine-dokka-extensions`

scripts/publish-documentation/publish.sh
This PR fixes a problem with the publish-documentation script. It removes the redundant checkout of the `1.x-dev` branch. This checkout is not required to fulfil the script's purpose. Moreover, it breaks the script if there is no such branch in the target repository.
=> Fix the publish-documentation script

scripts/publish-documentation/README.md, scripts/publish-documentation/publish.sh
This PR adds support for nested modules in the script for publishing Dokka documentation. This is done by changing the API  of the script, so it operates with paths to modules instead of module names. 
Also, this PR fixes a minor flaw with creating the `gh-pages` if it does not exist. The problem was with the script looking only through local branches which leads to the branch being created even if a remote one already exists.
=> Support nested modules when publishing Dokka documentation

buildSrc/src/main/resources/dokka/styles/custom-styles.css
This PR fixes a minor flaw with code blocks sticking to each other in Dokka's output. 
Before:
After:
=> Add margin to code blocks in Dokka documentation

buildSrc/src/main/kotlin/io/spine/internal/gradle/git/Config.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/git/Repository.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/git/UserInfo.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/RepositoryExtensions.kt
This PR addresses #383. 
The main issue was with using `com.google.api.client.util.Preconditions.checkArgument` in `io.spine.internal.gradle.git` package. Firstly, there is a built-in Kotlin function for doing the same thing. Secondly, this `checkArgument` depends on the Google API client library rather than Guava. This PR fixes this.
Also, there was a naming issue with `io.spine.internal.gradle.git.Config`. This PR removes the excessive nesting and leaves only the setting needed for our current needs.
=> Use idiomatic Kotlin preconditions

buildSrc/src/main/kotlin/io/spine/internal/gradle/git/Repository.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/git/UserInfo.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/RepositoryExtensions.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/Update.kt
This PR continues fixing issues with `io.spine.internal.gradle.git`. More specifically, it addresses comments of @alexander-yevsyukov in the #384 after it was merged. 
The first issue was using factory methods the following way `ClassName.Factory.of`. At the time of development, IDEA did not allow traversing from a companion object's documentation to the enclosing class' documentation. It seemed reasonable to state the `Factory` part explicitly. Currently, there is no such issue, so this part is removed.
The second issue was with the `UserInfo` factory method. This factory method, at this point, can be reduced to a simple validation in the `init{}` block.
=> Fix issues with `io.spine.internal.gradle.git`

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/CheckStyle.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt, quality/checkstyle-suppressions.xml, quality/checkstyle.xml
This PR configures Checkstyle to ignore generated code.
Bumps dependencies (checked under `core-java`).
=> Improve filtering for generated code

buildSrc/src/main/kotlin/deps-between-tasks.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/fs/LazyTempPath.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/RepositoryExtensions.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/Update.kt
This PR adds extension function for tentatively add dependencies between tasks created by ProtoData and Spine Model Compiler that are otherwise cause Gradle warnings in the console.
This extension was tried under `core-java` and `ProtoData` already.
=> Extend `Project` with `configureTaskDependencies()`

buildSrc/src/main/kotlin/deps-between-tasks.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR adds the dependency object `Spine` with the aim to standardize internal project dependencies across all repositories in the near future. 
The implementation was taken from `mc-java` and was slightly refactored for brevity.
=> Add `Spine` dependency object

.github/workflows/detekt-analysis.yml, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR improves the `Spine` dependency object to simplify its usage in projects that do not need all the version properties.
This was tested under `tool-base`.
=> Simplify `Spine` usage when no property defined

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR adds artifacts published from `core-java` to the `Spine` dependency class. Some module version were also bumped.
=> Add `core-java` modules to `Spine` dependency class

.idea/misc.xml, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/JUnit.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Jackson.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR updates dependencies:
* Protobuf was rolled back to `3.19.6` to address the absence of access modifiers in the generated code, so that the code can be used in projects with strict API mode.
* Jackson Databind and Jackson were bumed to address security reports.
* Dokka was bumped to `1.7.20`, the usability of this version was [tested under ProtoData](https://github.com/SpineEventEngine/ProtoData/pull/93).
* JUnit dependencies were bumed to latest release versions, allowing to use configurable `@TempDir` annotation.
* ProtoData was bumped to `0.2.20` so that projects can use Kotlin code gen (when [this PR](https://github.com/SpineEventEngine/ProtoData/pull/93) is merged).
=> Bump dependencies

.idea/dictionaries/common.xml, buildSrc/src/main/kotlin/io/spine/internal/dependency/ErrorProne.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR extends the `Spine` dependency object with recently introduced `change` module.
The spellcheck dictionary of IntelliJ IDEA was extended with words recently added in `core-java`.
Also ErrorProne was bumped to `2.16` (which was tested under `core-java`).
=> Add `change` to `Spine` dependency object

buildSrc/src/main/kotlin/io/spine/internal/gradle/testing/Tasks.kt
This PR extends configuration of JUnit for seeing test suites classes ending with `Spec`.
Also it fixes a couple of KDoc links (because Markdown does not seem to work in the `@see` tags).
=> Include test suites with `Spec` suffix

.github-workflows/build-on-ubuntu.yml, .github-workflows/build-on-windows.yml, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Pmd.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/testing/Tasks.kt
This PR updates PMD dependency and adds `*Spec` filter for unit test suites.
=> Bump PMD -> `6.50.0`, add `*Spec` tests

buildSrc/src/main/kotlin/deps-between-tasks.kt
This PR updates `buildSrc/.../deps-between-tasks.kt` to arrange conditional dependency of `sourceJar` on `prepareProtocConfigVersions`.
Some of the projects (like `mc-java`) need such a dependency, and this arrangement is needed to prevent accidental overwriting.
=> Depend `sourceJar` on `prepareProtocConfigVersions`

buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
This PR:
* Limits the artifacts to be found at `mavenLocal` to only `io.spine.*`.
* Rearranges repositories under `applyStandard()` so that `mavenCentral()` comes first, and `mavenLocal()` last.
Hopefully it would make our builds run a bit faster.
=> Use `mavenLocal()` for Spine artifacts only

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/GradleDoctor.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, gradle.properties
This PR adds dependency object for Gradle Doctor and improves `Spine` dependency object to handle McJava plugin.
=> Add Gradle Doctor, improve Spine

buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/javac/ErrorProne.kt
This PR extends `Repositories.kt` for allowing adding several GitHub artifact repositories in one call.
The aim is to make resolutions faster at CI. It's also give a bit more compact code.
=> Allow adding several GitHub repos at once

pull
I've just discovered that `pull` script copies ignored `detekt-code-analysis` workflow while shouldn't.
This changeset fixes a function that checks for existence of the given file or directory. Now it uses `-e` operator.
From [internet](https://linuxize.com/post/bash-check-if-file-exists/):
>When checking if a file exists, the most commonly used FILE operators are -e and -f. The first one will check whether a file exists regardless of the type, while the second one will return true only if the FILE is a regular file (not a directory or a device).
Also, instead of copying filtered workflows, the script now copies them all and then deletes the one that belongs only to `config`. It is for the case, when `.github` directory copied from scratch by `initialize .github` line above.
=> Fix false-positive check for `.github` directory existence in `pull` script

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
We add the dependency coordinates for the new `text` library.
=> Add `text` version

build.gradle.kts, buildSrc/src/main/kotlin/PluginsAccessors.kt.kt
This changeset updates escaped dependency objects to be plugin accessors. 
Reasoning is the following:
1. Those escaped dependencies seems to be used only in `plugins` sections, and the only way to use them there is to apply plugins.
2. Script-plugins also have such accessors generated along with the ones, provided by Gradle. Thus, in many cases, we can drop all `id(<string litaral>)` calls, making `plugins` section look coherent.
3. Custom versions can still be declared.
4. Names of those accessors should match [naming conventions](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:creating_a_plugin_id).
This change was previously adopted in [`base-types` #31](https://github.com/SpineEventEngine/base-types/pull/31).
=> Escape our dependency objects with plugin accessors

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/PluginsAccessors.kt, quality/detekt-config.yml
This changeset does the following:
1. Moves `protodata` and `mc-java` plugin accessors to the corresponding dependency accessors: `protoData` and `mcJava`. `mc-java` cannot be applied to a project directly. `protodata` can be, but when used in pair with `mc-java`, buildscript classpath ends up with both of them. Thus, making impossible direct apply of `protodata` too.
2. Updates Detekt config to exclude `*Extensions.kt` files from `TooManyFunctions` rule. Such files usually consists only of  functions.
=> Drop `protodata` and `mc-java` from plugins accessors and update Detekt config

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/PluginsAccessors.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/DependencyResolution.kt, quality/detekt-config.yml
This PR forces the version of Dokka base library. 
Dokka is widely used now among our modules and the same lib is usually forced.
By the way, this PR does the following:
1. Bumps `grGit` to `4.1.1`. The currently used version is not unavailable because JCenter is deprecated now. And bumping the version to the one, which is available in Maven Central, seems to be a good alternative to [registering](https://github.com/ajoberstar/grgit#old-versions-from-bintrayjcenter) another repository.
2. Allows long method names in `test` and `spec` sources.
3. Fixes numerous typos.
=> Force Dokka library

buildSrc/src/main/kotlin/io/spine/internal/gradle/RunGradle.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/IncrementGuard.kt, quality/detekt-config.yml
This PR updates Detekt config to exclude `*View.kt` and `*Projection.kt` files from `TooManyFunctions` rule.
Inheritors of `Projection` usually have a number of subscribing methods, so I propose to exclude them from this rule.
Also, this PR defines an [anchor](https://yaml.org/spec/1.2-old/spec.html#id2785586) for test and spec files to re-use them in filters to other rules.
=> Update Detekt configuration

gradle/wrapper/gradle-wrapper.properties
This PR bumps Gradle version to `7.6-rc-3`.
[Gradle 7.6-rc-3 Release Notes](https://docs.gradle.org/7.6-rc-3/release-notes.html).
=> Bump Gradle -> `7.6-rc-3`

buildSrc/src/main/kotlin/BuildExtensions.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Artifacts.kt
This PR:
* Updates internal and 3rd-party dependencies.
* Makes dependencies of tasks depending on `generateProto` explicit.
=> Bump gRPC and other dependencies

README.md, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, scripts/publish-documentation/README.md
This PR:
* Bumps versions of internal Spine SDK dependencies.
* Improves readability of the documentation for the `scripts/publish-documentation` directory.
=> Bump versions of subprojects

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, quality/detekt-config.yml
This PR:
* Extends detekt configuration to exclude `*Exts.ts` files from being checked for `TooManyFunctions`.
* Bumps detekt -> `1.22.0`.
* Bumps Kotlin -> `1.8.0.
* Bumps some Spine SDK subprojects.
=> Extend detekt configuration, bump versions

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt
This PR restores `Kotlin.stdLib7` and `Kotlin.stdLib7` properties which are still needed in subprojects for forcing versions, until all of them are migrated to Kotlin `1.8.0`.
Also, forcing these Kotlin artifacts in `buildSrc/build.gradle.kts` was removed because they are no longer applicable to Kotlin `1.8.0+`.
=> Restore `stdLibX` properties in `Kotlin` dependency object

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/javadoc/JavadocConfig.kt
This PR:
* Sets Oracle JDK Javadoc to be used for standard type links. The OpenJDK documentation site has expired certificate and is down time after time recently.
* Some versions of Spine SDK artifacts were also bumped.
=> Use Oracle JDK for Javadoc refs.

buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Artifacts.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/ProtoExts.kt, gradle/wrapper/gradle-wrapper.properties
This PR improves task dependency arrangements in `Artifacts.kt` to handle the case when Protobuf Gradle Plugin is not applied to a project. Also, Protobuf-related extensions functions are now gathered under `ProtoExts.kt` file.
These changes are tested under an in-progress PR in `mc-java`.
Also Gradle bumped to 7.6.1. See the [release notes](https://github.com/gradle/gradle/releases/tag/v7.6.1) for the issues this release fixes.
=> Depend on `generateProto` conditionally

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR bumps ProtoData version to `0.7.6`.
=> Bump ProtoData

buildSrc/src/main/kotlin/io/spine/internal/dependency/Pmd.kt, quality/pmd.xml
This PR bumps the version of PMD and  remove `ExcessiveClassLength` and `ExcessiveMethodLength` inspections because they are scheduled for removal in v7.0.
=> Bump `PMD` -> `6.55.0`

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR adds two properties for the `Spine` dependency object to address the appearance of new artifacts from `base`.
=> Add `spine-logging` and `spine-reflect`

scripts/publish-documentation/README.md, scripts/publish-documentation/publish.sh, scripts/publish-documentation/sample-publishing-1.x-repos.sh.template
This changeset updates Dokka publishing script.
Previously, Dokka output was always residing in `dokka` sub-folder. However, starting from some version of Dokka (and it's not too easy to tell from which exactly), the output for Java code is now located in `dokkaJava`.
This PR addresses this change in Dokka behaviour by modifying `publish.sh` script accordingly.
Other changes:
* More logging was added to the publishing script in order to better track potential failures.
* Samples on using `publish.sh` for `1.x` artifacts were added, so that end-users spend less time searching for proper parameter values.
=> Adjust Dokka publishing according to the latest Dokka changes

.github-workflows/build-on-ubuntu.yml, .github-workflows/build-on-windows.yml, .github-workflows/ensure-reports-updated.yml, .github-workflows/increment-guard.yml, .github/workflows/detekt-code-analysis.yml, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR:
— Add names for the GitHub Workflow jobs so that we can add them as required pre-merge checks.
— Bumps versions of Spine modules in the dependency object.
=> Add job names

buildSrc/src/main/kotlin/io/spine/internal/dependency/Okio.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/OsDetector.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Plexus.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Slf4J.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/task/IntegrationTest.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/Update.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/task/IntegrationTest.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/task/LicenseReport.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/task/Webpack.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/report/license/ModuleDataExtensions.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/report/pom/PomGenerator.kt
This PR addresses warnings reported in a project which uses `config` after applying the latest version. The goal is to minimise the analysis time required to dismiss these warnings as false flags.
=> Address warnings

.lift.toml, buildSrc/src/main/kotlin/io/spine/internal/dependency/Guava.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Validation.kt
This PR:
* Bumps versions of internal dependencies.
* Adds links to repositories in the `Spine` dependency object.
* Removes Sonatype Lift configuration file.
* Suppresses `ConstPropertyName` warning according to [our convention](https://github.com/SpineEventEngine/documentation/wiki/Kotlin-code-style#property-names-for-dependency-objects). 
* Bumps dependencies on ProtoData and other internal SDK artifacts.
* Bumps dependencies on Guava, Protobuf, and Protobuf Gradle Plugin.
=> Repo links in KDocs, bump dependencies

buildSrc/src/main/kotlin/io/spine/internal/dependency/Roaster.kt, gradle/wrapper/gradle-wrapper.properties
Since Spine no longer tied to Java 8, we can bump the version from `2.24.0.Final` (which was the last supporting Java 8 on the level of binaries) to the latest one. This resolves #220.
Gradle was also bumped to `7.6.2`.
=> Bump Roaster -> `2.28.0.Final`

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR:
* Bumps build script dependencies declared in `buildSrc/src/build.gradle.kts`.
* Bumps Spine and ProtoData.
The changes are tested under ProtoData and `mc-java`.
=> Bump build script and internal dependencies

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR introduces `Spine.Logging` dependency object to gather multiple artifacts produced by this subproject under its "umbrella".
=> `Logging` dependency object

buildSrc/src/main/kotlin/DependencyResolution.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Asm.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/jvm-module.gradle.kts
This PR bumps the version of `spine-logging` to the latest one, in which the published library is operational again.
Also, it substitutes a runtime dependency on Flogger's JUL backend with Spine Logging. In general, specifying of a backend makes no sense unless a facade is used. I think we can go with the following options:
1. Configure Spine logging by default with our facade and JUL backend. This option is employed in this PR.
2. Doesn't pre-configure logging at all. Remove specifying of Flogger's backend.
We **potentially can** detect which facade is used, and then specify the corresponding backend in `jvm-module`. But this will have to be done with `project.afterEvaluate { ... }` closure. Because if `jvm-module` doesn't dictate the used facade, then a concrete module is meant to …
=> Bump Spine Logging

.github-workflows/build-on-windows.yml, buildSrc/src/main/kotlin/DependencyResolution.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt, pull
This PR adopts the pagefile configuration when building under Windows. It was recently adopted for `mc-java` because of memory issues during Windows build at GitHub.
Other changes:
* Bump ProtoData -> `0.9.9`
* Do not copy `.lyft.toml` on `pull`.
=> Configure page file for Windows build

.idea/misc.xml, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Validation.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/Runtime.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/javadoc/ExcludeInternalDoclet.kt, buildSrc/src/main/kotlin/jvm-module.gradle.kts, pull
This PR:
* Bumps gRPC.
* Bumps internal dependencies.
* Improves `Runtime.kt` file removing unused code and making it more idiomatic for Kotlin.
* Makes `ExcludeInternalDoclet` class to use artifact declared in `Spine` object.
* Extends `pull` script to take care of removal of `.lift.toml` file.
=> Small fixes

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR adds a newly created smoke test library to `Spine.Logging`. Spine modules can use this dependency to add logging smoke test to their own tests.
Take a look on [README](https://github.com/SpineEventEngine/logging/tree/master/tests/logging-smoke-test) to `logging-smoke-test` to know how to do that.
=> Add `smokeTest` lib to `Spone.Logging`

buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt
In this PR we make the `buildSrc`'s script `ProtoData` choose which version of ProtoData to use, a public remote one or one published locally.
In order to switch to the locally published version, declare the `PROTO_DATA_VERSION` env variable (or the `PROTO_DATA_DF_VERSION`) with the desired version. The script will handle the rest.
=> Local ProtoData versions

buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Validation.kt
This PR removes redundant underscore in the names of environment variables which ProtoData uses for running in a locally deployed version.
Other changes:
* Internal dependencies were bumped.
* `Spine.Logging` got `grpcContext` property, partially addressing #489.
=> Fix environment variables for ProtoData local mode

buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR does the following:
1. Adds Log4j2 backend to `Spine.Logging`.
2. Deprecates usage of `Spine.Logging.floggerApi`. Now, it is a transitive dependency for `spine-logging`. And I can't say why anyone would need it explicitly.
3. Fixes env names in a code snippet to `ProtoData`.
=> Add Log4j2 backend to `Spine.Logging` dependency object

buildSrc/src/main/kotlin/io/spine/internal/dependency/Roaster.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR:
* Rolls back Roaster to `2.28.0.Final`, which is the last version build with Java 11.
* Bumps Spine Logging to `2.0.0-SNAPSHOT.186`.
=> Rollback `Roaster`, bump `Logging`

build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/jvm-module.gradle.kts
This PR bumps `spine-logging` to `2.0.0-SNAPSHOT.232` and updates its artifacts.
=> Bump `spine-logging`

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/internal/dependency/AssertK.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/CheckStyle.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/CheckerFramework.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ErrorProne.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/FindBugs.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Flogger.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Gson.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Guava.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/HttpClient.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/J2ObjC.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Jackson.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/JavaJwt.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotest.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kover.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Netty.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Okio.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Plexus.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Validation.kt, buildSrc/src/main/kotlin/jvm-module.gradle.kts
This PR applies dependencies recently tried `core-java` with the aim of propagation these changes to other Spine SDK subprojects.
=> Apply dependencies tried in `core-java`

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/DependencyResolution.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/J2ObjC.kt
This PR adds the Shadow plugin to the `buildSrc/build.gradle.kts` so that it's not erased by `config` update in Validation and other subprojects.
Also this PR forces transitive dependencies of `com.google.cloud.artifactregistry:artifactregistry-auth-common`, we we cannot bump after `2.1.5` because of breaking changes. For now we're safe, but `artifactregistry-auth-common` needs to be updated sometime to minimise the "noise" in the build code.
=> Add Shadow plugin, force transitive dependencies

.github-workflows/ensure-reports-updated.yml, buildSrc/src/main/kotlin/io/spine/internal/gradle/report/license/Paths.kt, pull, scripts/ensure-reports-updated.sh
According to #498, `license-report.md` is renamed to `dependencies.md` within this changeset.
Additionally, the CI workflows are now configured to check than either `license-report.md` (for non-migrated repos, which still use this file) or `dependencies.md` is modified within the changeset.
`pull` script has been modified to kill `license-report.md` file. 
:warning: `config` end-users will have to add a newly generated `dependencies.md` to Git themselves.
=> Write dependency-license report to `dependencies.md`

buildSrc/src/main/kotlin/DependencyResolution.kt
This PR forces `kotlin-stdlib-jdk7` dependency version.
As it turns out, this dependency comes as conflicting in at least `base`, `reflect` (!), and `logging` libraries. Apparently, some of our direct dependencies brings the old version of this library with it.
After some attempts to find out, which dependency is "guilty", I gave up, as no clear answer is available. So it's easier to force its version.
=> Force Kotlin `stdlib-jdk7` dependency version

.idea/kotlinc.xml, buildSrc/src/main/kotlin/io/spine/internal/dependency/IntelliJ.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
This PR extends `buildSrc` code with dependencies and repositories required to add IntelliJ PSI to a project.
Some other dependencies were also bumped.
=> Add PSI dependencies

buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt
This PR adds `ProtoData.fatCli` property which is used in Validation to avoid accidental removal when updating `config`.
The version of ProtoDat dependency was also bumped to recently published `0.16.0`.
=> Add `fatCli` property for ProtoData dependency object

buildSrc/src/main/kotlin/io/spine/internal/gradle/protobuf/ProtoTaskExtensions.kt
At the moment, not all Spine libraries are able to use Spine McJava plugin — due to the cyclic dependencies otherwise introduced. But simultaneously, libraries like `tool-base` and `base-types` provide their own Proto language, and hence, must bring respective descriptor set files with them.
This issue has been addressed very inconsistently throughout the repositories, leading to mis-interpretation of descriptor set files, or failures to locate them at all.
This changeset improves the descriptor set generation by doing the following.
* For the descriptor set file name, a Maven coordinates of the respective artifact are used. Previously, we used `known_types_{sourceSetName}.desc` everywhere, which caused clashes.
* Generate a new `desc.ref` file referencing the generated descriptor set …
=> Improve the generation of descriptor set files for "simple" Spine libraries

buildSrc/src/main/kotlin/DokkaExts.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Validation.kt
This PR introduces `Project.disableDocumentationTasks()` extension function which allows to disable tasks having `"dokka"` and `"javadoc"` (case insensitive) in their names. This would allow improving build speed switching off documentation in test environment and integration test modules.
Also versions of internal dependencies were bumped.
=> Add `Project` extension for disabling documentation tasks

.gitignore, buildSrc/build.gradle.kts
This changeset equips `buildSrc/build.gradle.kts` with another `implementation`-level dependency, which allows to shorten the build time for integration tests by re-using `buildSrc.jar` instead of re-compiling Kotlin sources in `buildSrc/src`.
=> Depend on `buildSrc.jar` in case `src` is missing

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Repositories.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Coroutines.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/GrpcKotlin.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/IntelliJ.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Jackson.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Publications.kt, buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/SpinePublishing.kt, buildSrc/src/main/kotlin/write-manifest.gradle.kts
This PR brings changes recently introduced in `tool-base` ([1](https://github.com/SpineEventEngine/tool-base/pull/79), [2](https://github.com/SpineEventEngine/tool-base/pull/80)).
=> Add recent changes to `buildSrc` from `tool-base`

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
This PR adds `psiJava` and `psiJavaBundle` properties to `Spine` dependency object. These properties were recently introduced in `tool-base` and then adopted in code generation subprojects.
Other notable changes:
* Deprecated properties on Logging belonging to `Spine` object directly were eliminated.
=> Add `psiJava` and `psiJavaBundle` properties to `Spine`

buildSrc/src/main/kotlin/io/spine/internal/gradle/kotlin/KotlinConfig.kt
This PR improves passing `freeCompilerArgs` in `KotlinCompile.setFreeCompilerArgs()` extension function. Previously, we always passed the flag, which resulted in "unsupported flag" warning emitted by Kotlin compilers before 1.9.20. 
Now the flag is added depending on the current Kotlin version.
=> Do not use flag `-Xexpect-actual-classes` Kotlin compiler flag before 1.9.20

.github-workflows/build-on-ubuntu.yml, .github-workflows/build-on-windows.yml, .github-workflows/ensure-reports-updated.yml, .github-workflows/increment-guard.yml, .github-workflows/publish.yml, .github/workflows/detekt-code-analysis.yml, .github/workflows/gradle-wrapper-validation.yml
This PR bumps `checkout` and `setup-java` actions to `@v4`. These versions were tried in recent PRs on ProtoData and McJava.
=> Bump `checkout` and `setup-java` to `@v4`

.github-workflows/build-on-ubuntu.yml
This changeset updates the Codecov GitHub Actions to v4.
All the uploads made via the previous v3 version seem to work improperly, or just stumble across refusal to accept the coverage payload. This happened because the token-less uploads are no longer supported (see [their official docs on v4 release](https://github.com/codecov/codecov-action?tab=readme-ov-file#v4-release)). 
Therefore, this PR also includes the token value into the Actions script configuration.
The token is set up on the organizational level for all public repositories of SpineEventEngine.
Prior to creating this PR, the same code was successfully tested in our `base` repository.
=> Migrate to Codecov v4, supply this action with a token

buildSrc/src/main/kotlin/BuildExtensions.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Aedile.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Auto.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Ksp.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/LicenseReport.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoTap.kt, buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt, buildSrc/src/main/kotlin/jacoco-kotlin-jvm.gradle.kts
This PR brings `buildSrc` updates recently adopted in ProtoData, McJava, and Validation.
=> Adopt improvements from subprojects

scripts/buildSrc-migration.kts
This PR fixes the placement of the `Clikt` dependency in the migration script.
=> Fix placement of `Clikt` in migration script

.github-workflows/remove-obsolete-artifacts-from-packages.yaml, scripts/request-package-names.sh
As noted in #522, many non-release artifacts in Spine's GitHub Packages are obsolete and no longer in use. 
This changeset introduces a GitHub Actions workflow to automate the removal of these obsolete non-release artifacts from GitHub Packages.
An artifact is considered non-releasable if it includes the word “SNAPSHOT” in its version name. The workflow is scheduled to run daily at midnight. The removal task retains the five most recent non-release artifacts.
The artifact removal process follows these steps:
1. Retrieves the names of packages created from this repository.
2. For each package published from this repository, initiates a separate job to remove obsolete artifacts.
Additional details:
1. Artifacts that are public and have been downloaded more than 5,000 times cannot be …
=> Remove obsolete Maven artifacts from GitHub Packages

.github/workflows/gradle-wrapper-validation.yml, buildSrc/src/main/kotlin/io/spine/dependency/lib/KotlinX.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/McJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt
This PR migrates Gradle Wrapper validation to `wrapper-validation@v4`.
Also, several local dependencies were bumped.
=> Use  `wrapper-validation@v4`

buildSrc/src/main/kotlin/io/spine/dependency/lib/Auto.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Log4j2.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ArtifactVersion.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/CoreJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Logging.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ToolBase.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt, buildSrc/src/main/kotlin/io/spine/gradle/kotlin/KotlinConfig.kt, buildSrc/src/main/kotlin/io/spine/gradle/publish/CloudRepo.kt
This PR propagates small improvements recently made under `buildSrc` in ToolBase and ProtoData projects. 
Also this PR promotes latest versions of Base, ToolBase, CoreJava, and ProtoData.
=> Propagate recent improvements from ToolBase and ProtoData. Use latest local dependencies

.idea/inspectionProfiles/Project_Default.xml, buildSrc/src/main/kotlin/io/spine/dependency/local/McJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt, buildSrc/src/main/kotlin/io/spine/gradle/publish/CheckVersionIncrement.kt, buildSrc/src/main/kotlin/io/spine/gradle/publish/SpinePublishing.kt
This PR fixes the issue with checking for the increment of the version. Previously, the code of `CheckVersionIncrement` task always assumed `spine-` prefix. A project could have a custom prefix for publishing which should be taken into account.
Also, the PR advances versions of recently updated compiler modules.
=> Take custom artifact prefix when checking for version increment

buildSrc/src/main/kotlin/io/spine/dependency/local/TestLib.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ToolBase.kt
This PR bumps versions of local dependencies that were advanced recently in relation code generation works in  ProtoData and Validation.
=> Bump local dependencies

buildSrc/src/main/kotlin/BuildExtensions.kt, buildSrc/src/main/kotlin/BuildSettings.kt, buildSrc/src/main/kotlin/DokkaExts.kt, buildSrc/src/main/kotlin/io/spine/dependency/build/Ksp.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/KotlinX.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/McJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoTap.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ToolBase.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt, buildSrc/src/main/kotlin/io/spine/dependency/test/KotlinCompileTesting.kt
This PR adds changes [recently made in McJava ](https://github.com/SpineEventEngine/mc-java/pull/186) for propagating to other projects.
* `Project.configureTaskDependencies()` extension in `BuildExtensions.kt` was extended to support dependencies with KSP tasks.
* `AbstractDokkaTask.isInPublishingGraph()` now considers only `publish` as the publishing task.
* `BuildSettings` got a property for using with compatibility properties when configuring Java.
* The `Kotlin` dependency object got more entries and deprecations.
* `KotlinCompileTesting` now comes from [https://github.com/zacsweers/kotlin-compile-testing] instead of [https://github.com/tschuchortdev/kotlin-compile-testing] because the fork from Zac Sweers is maintained better.
=> Bring changes from McJava

.gitignore, .idea/kotlinc.xml, .idea/misc.xml, buildSrc/src/main/kotlin/BuildExtensions.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/CoreJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/McJava.kt, buildSrc/src/main/kotlin/io/spine/gradle/RunBuild.kt, buildSrc/src/main/kotlin/io/spine/gradle/RunGradle.kt, buildSrc/src/main/kotlin/io/spine/gradle/report/pom/DependencyWriter.kt, buildSrc/src/main/kotlin/io/spine/gradle/report/pom/ModuleDependency.kt
The major change this PR introduces is making the function `RunGradle.execute()` which is annotated `@TaskAction` `public`. This is a requirement of latest versions of Gradle. Previously the function was `private` without coplaints.
* Add nullability of dependency version in `ModuleDependency.kt` with relevant changes in `DependencyWriter.kt`.
* `RunBuild` now executes the `clean` task before `build`.
* The dependency of `dokkaKotlinJar` on `dokkaJavdoc` was removed because it provide to be circular when building ProtoData.
=> Make task action `public`

buildSrc/src/main/kotlin/BuildExtensions.kt, buildSrc/src/main/kotlin/io/spine/dependency/build/Ksp.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/McJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt
This PR copies updates to `buildSrc` recently made in McJava so that they are propagated to other subprojects.
=> Bring `buildSrc` updates from latest McJava

buildSrc/src/main/kotlin/io/spine/gradle/protobuf/ProtoTaskExtensions.kt
This PR brings the change made to the `GenerateProtoTask.setup()` extension recently adopted in Base. 
The change addresses the `ConcurrentModificationException`, which appeared recently when migrating to Gradle 8.13.
=> Improve `GenerateProtoTask.setup()` under `buildSrc`

buildSrc/build.gradle.kts
This PR bumps the version of Kotlin used for the build to `2.1.20`.
=> Bump Kotlin under `buildSrc`

.gitignore, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/BuildExtensions.kt, buildSrc/src/main/kotlin/io/spine/dependency/build/PluginPublishPlugin.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Grpc.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/test/JUnit.kt, buildSrc/src/main/kotlin/io/spine/gradle/publish/PublishingExts.kt, buildSrc/src/main/kotlin/jvm-module.gradle.kts, gradle.properties, pull, quality/pmd.xml, scripts/JSpecify-migration.kts
This PR updates the `pull` script to propagate `gradle.properties` and `.gitignore` to the subprojects.
Also, versions of Guava and Jackson used in the `buildSrc/build.gradle.kts` were sync'ed with versions in the dependency objects.
* Kover DSL was updated to match the latest version.
* Give more memory for Dokka in `gradle.properties`.
* Remove removal instructions for long outdated scripts under the `pull` script.
* Improve exclusions in `JSpecify-migration.kts`.
* Added `PluginPublishPlugin` dependency object and `plugin-publish` extension.
* `PublishingExts.kts` was copied from `tool-base`.
=> Propagate `gradle.properties` and `.gitignore`

.gitignore, .idea/codeStyles/Project.xml, buildSrc/src/main/kotlin/BuildExtensions.kt, buildSrc/src/main/kotlin/DependencyResolution.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/GrpcKotlin.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Jackson.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/test/JUnit.kt, buildSrc/src/main/kotlin/io/spine/gradle/publish/PublishingExts.kt, buildSrc/src/main/kotlin/io/spine/gradle/report/pom/PomGenerator.kt, buildSrc/src/main/kotlin/module-testing.gradle.kts
This PR rolls back the version of gRPC for Kotlin to 1.4.1 becuse 1.4.2 is not available from public Maven repositories.
Also this PR forces the line separators in the settings because pulling `config` recently gives many warnings about encountered Windows line separators. Let's stick to Unix separators to avoid the noise.
* `JUnit` and `Jackson` dependency objects were updated assuming we are going to force them as platforms.
* `DependencyResolution` was updated accordingly to the previous item.
* `module-testing` conventions plugin was added for being used for configuring testing in a JVM module.
* Ignore `**/.kotlin/` directories instead of only files under them.
* Ignore generated Dart code. This is brought from `base`.
* Remove redundant entries in `.gitignore`.
=> Rollback gRPC Kotlin and force line separators to Unix

buildSrc/src/main/kotlin/io/spine/dependency/lib/GrpcKotlin.kt
This PR restores the suffix, which was accidentally removed in the previous PR.
=> Restore gRPC `protoc` plugin artifact suffix

.gitattributes, buildSrc/src/main/kotlin/module-testing.gradle.kts, migrate, pull
This PR extract the migration code from the `pull` script into a separate `migrate` script so that it does not take running `pull` two times to execute the migration part removing old files etc.
* `.gitattributes` file was updated so that it knows about Kotlin, Kotlin Script, and SVG formats.
* Forcing JUnit via BOM now is done using `platform()` instead of `enforcePlatform()` which proved to be too hard.
=> Separate migration code from `pull`

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/dependency/lib/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ToolBase.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt, buildSrc/src/main/kotlin/io/spine/gradle/publish/PublicationHandler.kt
This PR adds new version of `SpinePublishing` project extension which was recently adopted in `tool-base`.
* Local dependencies were bumped to latests versions.
* Protobuf library version was revered from `4.30.2` to `3.25.7` so that we can migrate tools which depend on `GeneratedVersionV3` API.
* The version of Protobuf Gradle Plugin was kept at `0.9.5` because latest `tool-base` provides backward compatibility support.
=> Apply improved `SpinePublishing` from `tool-base`

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/jvm-module.gradle.kts
This PR fixes the dependency passed in the `jvm-module` conventions plugin to `kover()`. 
Previously it was used just `this`, which in context of `rootProject.dependencies` was of the type `DependencyHandlerScope`. This resulted in the build failure in the project to which `config` was applied.
The correct `this` is `this@configureKotlin` which refers to the `Project` to which the `configureKotlin()` extension function is applied.
* The version of ErrorProne Gradle Plugin was bumped to [`4.2.0`](https://github.com/tbroyer/gradle-errorprone-plugin/releases/tag/v4.2.0) because of the following reason:
> This is [in preparation for Gradle 8.14](https://docs.gradle.org/8.14-rc-2/release-notes.html#configurations-are-initialized-lazily) which will no longer realize all configurations in the …
=> Fix `kover` dependency

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/DependencyResolution.kt, buildSrc/src/main/kotlin/io/spine/dependency/boms/Boms.kt, buildSrc/src/main/kotlin/io/spine/dependency/boms/BomsPlugin.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Kotlin.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Protobuf.kt, buildSrc/src/main/kotlin/io/spine/dependency/test/JUnit.kt, buildSrc/src/main/kotlin/jvm-module.gradle.kts, buildSrc/src/main/kotlin/module-testing.gradle.kts
This PR adds changes and additions recently introduced when resolving dependency conflicts when building [new version of `base-types`](https://github.com/SpineEventEngine/base-types/pull/44).
=> Bring improvements from `base-types`

buildSrc/src/main/kotlin/io/spine/dependency/boms/BomsPlugin.kt, buildSrc/src/main/kotlin/io/spine/dependency/kotlinx/Coroutines.kt, buildSrc/src/main/kotlin/io/spine/dependency/lib/Kotlin.kt
This PR brings latest updates to the `buildSrc` content that were [adopted in the Base subproject](https://github.com/SpineEventEngine/base/pull/876).
=> Bring updates from `base`

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/spine/dependency/build/Ksp.kt
This PR advances the version of KSP to be compatible with the latest version of Kotlin. 
Also the PR bumps the version of Protobuf Gradle Plugin used by the build via the `classpath` dependency of `buildSrc` to `0.9.5`.
=> Bump KSP and Protobuf Gradle Plugin of the build

buildSrc/src/main/kotlin/BuildExtensions.kt, buildSrc/src/main/kotlin/io/spine/dependency/build/Ksp.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/CoreJava.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Time.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ToolBase.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt, gradle.properties
This PR brings changes in `buildSrc` recently adopted in ProtoData. Also, it adds the flag in `gradle.properties` turning on parallel build task execution.
=> Updates from ProtoData

.junie/guidelines.md, AGENTS.md, buildSrc/build.gradle.kts, buildSrc/settings.gradle.kts, buildSrc/src/main/kotlin/io/spine/dependency/build/Ksp.kt, buildSrc/src/main/kotlin/io/spine/dependency/local/ToolBase.kt
This PR consolidates the guidelines for Junie and other agents, following the feedback from Junie and GPT-4o.
* Newer Shadow plugin version was applied.
* `buildSrc` got the `settings.gradle.kts` with the Foojay resolver plugin.
* KSP was bumped -> `2.1.21-2.0.2`.
* `ToolBase` dependency object got properties after the latest ToolBase module structure.
=> Improve Agent guidelines and ToolBase structure
